import type { WeekFacts } from '@/lib/content/types';

/**
 * Language-independent facts for weeks 1–40.
 *
 * Nothing here is prose: every reader-facing sentence is looked up in the
 * per-locale phrase book (`./phrasebook`). That keeps 6 × 40 week pages
 * genuinely localised instead of translated from one English master text,
 * and lets the medical facts be reviewed in one place.
 *
 * Measurements: crown-rump length through week 20, crown-heel from week 21 —
 * the convention used by most antenatal references. They are averages; real
 * babies vary widely.
 */
export const WEEK_FACTS: WeekFacts[] = [
  {
    week: 1,
    trimester: 1,
    sizeKey: 'not_yet',
    lengthCm: null,
    weightG: null,
    developmentKeys: ['prep_cycle'],
    bodyKeys: ['period_starts', 'uterus_lining_sheds'],
    symptomKeys: ['period_symptoms', 'fatigue', 'mood_swings'],
    tipKeys: ['start_folic_acid', 'track_cycle', 'avoid_alcohol_smoking'],
  },
  {
    week: 2,
    trimester: 1,
    sizeKey: 'not_yet',
    lengthCm: null,
    weightG: null,
    developmentKeys: ['egg_released', 'ovulation'],
    bodyKeys: ['fertile_window', 'cervical_mucus_changes'],
    symptomKeys: ['ovulation_signs', 'breast_tenderness', 'increased_appetite'],
    tipKeys: ['track_cycle', 'gentle_movement', 'prenatal_vitamin'],
  },
  {
    week: 3,
    trimester: 1,
    sizeKey: 'not_yet',
    lengthCm: null,
    weightG: null,
    developmentKeys: ['fertilization', 'cell_division'],
    bodyKeys: ['hormones_rising', 'uterus_lining_thickens'],
    symptomKeys: ['no_symptoms_yet', 'bloating', 'light_spotting'],
    tipKeys: ['prenatal_vitamin', 'avoid_alcohol_smoking', 'hydrate'],
  },
  {
    week: 4,
    trimester: 1,
    sizeKey: 'poppy_seed',
    lengthCm: 0.1,
    weightG: null,
    developmentKeys: ['implantation', 'placenta_begins', 'three_layers_form'],
    bodyKeys: ['hcg_detectable', 'missed_period_soon'],
    symptomKeys: ['light_spotting', 'breast_tenderness', 'fatigue'],
    tipKeys: ['take_test', 'book_first_appointment', 'avoid_alcohol_smoking'],
    milestoneKey: 'implantation_milestone',
  },
  {
    week: 5,
    trimester: 1,
    sizeKey: 'sesame_seed',
    lengthCm: 0.3,
    weightG: null,
    developmentKeys: ['neural_tube_forms', 'heart_begins_beating', 'circulation_starts'],
    bodyKeys: ['hormones_rising', 'blood_volume_rises'],
    symptomKeys: ['fatigue', 'nausea', 'frequent_urination'],
    tipKeys: ['small_frequent_meals', 'rest_when_tired', 'prenatal_vitamin'],
  },
  {
    week: 6,
    trimester: 1,
    sizeKey: 'lentil',
    lengthCm: 0.5,
    weightG: null,
    developmentKeys: ['heart_begins_beating', 'arm_leg_buds', 'facial_features_form'],
    bodyKeys: ['uterus_grows_slightly', 'breast_changes'],
    symptomKeys: ['nausea', 'heightened_smell', 'mood_swings'],
    tipKeys: ['small_frequent_meals', 'hydrate', 'book_first_appointment'],
  },
  {
    week: 7,
    trimester: 1,
    sizeKey: 'blueberry',
    lengthCm: 1.3,
    weightG: null,
    developmentKeys: ['brain_grows_fast', 'arm_leg_buds', 'kidneys_form'],
    bodyKeys: ['mucus_plug_forms', 'breast_changes'],
    symptomKeys: ['nausea', 'fatigue', 'food_aversions'],
    tipKeys: ['rest_when_tired', 'small_frequent_meals', 'gentle_movement'],
  },
  {
    week: 8,
    trimester: 1,
    sizeKey: 'raspberry',
    lengthCm: 1.6,
    weightG: 1,
    developmentKeys: ['fingers_toes_webbed', 'tail_disappears', 'spontaneous_movements'],
    bodyKeys: ['uterus_size_orange', 'blood_volume_rises'],
    symptomKeys: ['nausea', 'bloating', 'breast_tenderness'],
    tipKeys: ['first_scan_booking', 'hydrate', 'avoid_alcohol_smoking'],
  },
  {
    week: 9,
    trimester: 1,
    sizeKey: 'grape',
    lengthCm: 2.3,
    weightG: 2,
    developmentKeys: ['all_organs_present', 'heartbeat_audible_scan', 'muscles_develop'],
    bodyKeys: ['hormones_rising', 'uterus_size_orange'],
    symptomKeys: ['fatigue', 'mood_swings', 'nausea'],
    tipKeys: ['gentle_movement', 'small_frequent_meals', 'talk_about_worries'],
  },
  {
    week: 10,
    trimester: 1,
    sizeKey: 'kumquat',
    lengthCm: 3.1,
    weightG: 4,
    developmentKeys: ['embryo_becomes_fetus', 'fingernails_start', 'bones_hardening'],
    bodyKeys: ['uterus_size_orange', 'skin_changes_body'],
    symptomKeys: ['nausea', 'headaches', 'constipation'],
    tipKeys: ['fiber_rich_foods', 'hydrate', 'prenatal_vitamin'],
    milestoneKey: 'fetus_milestone',
  },
  {
    week: 11,
    trimester: 1,
    sizeKey: 'fig',
    lengthCm: 4.1,
    weightG: 7,
    developmentKeys: ['fingers_toes_separate', 'tooth_buds_form', 'spontaneous_movements'],
    bodyKeys: ['blood_volume_rises', 'waist_thickens'],
    symptomKeys: ['heartburn', 'fatigue', 'increased_appetite'],
    tipKeys: ['first_trimester_screening', 'iron_rich_foods', 'gentle_movement'],
  },
  {
    week: 12,
    trimester: 1,
    sizeKey: 'lime',
    lengthCm: 5.4,
    weightG: 14,
    developmentKeys: ['reflexes_begin', 'kidneys_make_urine', 'vocal_cords_form'],
    bodyKeys: ['uterus_rises_pelvis', 'nausea_may_ease'],
    symptomKeys: ['nausea_easing', 'dizziness', 'nasal_congestion'],
    tipKeys: ['first_scan_booking', 'tell_employer', 'sleep_on_side'],
    milestoneKey: 'first_trimester_end',
  },
  {
    week: 13,
    trimester: 2,
    sizeKey: 'lemon',
    lengthCm: 7.4,
    weightG: 23,
    developmentKeys: ['fingerprints_form', 'external_genitals_form', 'bones_hardening'],
    bodyKeys: ['energy_returns', 'showing_starts'],
    symptomKeys: ['increased_appetite', 'nasal_congestion', 'breast_tenderness'],
    tipKeys: ['maternity_clothes', 'gentle_movement', 'hydrate'],
    milestoneKey: 'second_trimester_start',
  },
  {
    week: 14,
    trimester: 2,
    sizeKey: 'peach',
    lengthCm: 8.7,
    weightG: 43,
    developmentKeys: ['facial_expressions', 'lanugo_appears', 'sucking_reflex'],
    bodyKeys: ['energy_returns', 'uterus_grows_steadily'],
    symptomKeys: ['round_ligament_pain', 'forgetfulness', 'skin_changes'],
    tipKeys: ['moisturise_skin', 'pelvic_floor_exercises', 'iron_rich_foods'],
  },
  {
    week: 15,
    trimester: 2,
    sizeKey: 'apple',
    lengthCm: 10.1,
    weightG: 70,
    developmentKeys: ['hearing_begins', 'taste_buds_form', 'coordinated_movements'],
    bodyKeys: ['blood_volume_rises', 'nasal_membranes_swell'],
    symptomKeys: ['nosebleeds', 'heartburn', 'leg_cramps'],
    tipKeys: ['talk_and_sing', 'hydrate', 'gentle_movement'],
  },
  {
    week: 16,
    trimester: 2,
    sizeKey: 'avocado',
    lengthCm: 11.6,
    weightG: 100,
    developmentKeys: ['hears_your_voice', 'eyes_move_slowly', 'bones_hardening'],
    bodyKeys: ['fundal_height_navel', 'showing_starts'],
    symptomKeys: ['round_ligament_pain', 'back_ache', 'increased_appetite'],
    tipKeys: ['anomaly_scan_booking', 'sleep_on_side', 'pelvic_floor_exercises'],
  },
  {
    week: 17,
    trimester: 2,
    sizeKey: 'pear',
    lengthCm: 13,
    weightG: 140,
    developmentKeys: ['fat_under_skin', 'umbilical_cord_thickens', 'sweat_glands_form'],
    bodyKeys: ['ligaments_soften', 'balance_shifts'],
    symptomKeys: ['back_ache', 'dizziness', 'vivid_dreams'],
    tipKeys: ['supportive_shoes', 'gentle_movement', 'small_frequent_meals'],
  },
  {
    week: 18,
    trimester: 2,
    sizeKey: 'bell_pepper',
    lengthCm: 14.2,
    weightG: 190,
    developmentKeys: ['hearing_sharpens', 'myelin_forms', 'yawning_hiccups'],
    bodyKeys: ['first_movements', 'appetite_grows'],
    symptomKeys: ['leg_cramps', 'swollen_ankles', 'back_ache'],
    tipKeys: ['anomaly_scan', 'hydrate', 'rest_and_elevate_feet'],
  },
  {
    week: 19,
    trimester: 2,
    sizeKey: 'mango',
    lengthCm: 15.3,
    weightG: 240,
    developmentKeys: ['vernix_forms', 'brain_maps_senses', 'hair_on_head'],
    bodyKeys: ['first_movements', 'skin_pigment_changes'],
    symptomKeys: ['skin_changes', 'hip_pain', 'heartburn'],
    tipKeys: ['sun_protection', 'moisturise_skin', 'sleep_on_side'],
  },
  {
    week: 20,
    trimester: 2,
    sizeKey: 'banana',
    lengthCm: 25.6,
    weightG: 300,
    developmentKeys: ['swallowing_practice', 'hair_on_head', 'coordinated_movements'],
    bodyKeys: ['uterus_at_navel', 'weight_gain_steady'],
    symptomKeys: ['back_ache', 'shortness_breath', 'discharge_increase'],
    tipKeys: ['anomaly_scan', 'start_kick_awareness', 'birth_plan'],
    milestoneKey: 'halfway',
  },
  {
    week: 21,
    trimester: 2,
    sizeKey: 'carrot',
    lengthCm: 26.7,
    weightG: 360,
    developmentKeys: ['rapid_weight_gain', 'taste_through_fluid', 'marrow_makes_blood'],
    bodyKeys: ['braxton_hicks', 'appetite_grows'],
    symptomKeys: ['stretch_marks_itch', 'leg_cramps', 'varicose_veins'],
    tipKeys: ['moisturise_skin', 'gentle_movement', 'iron_rich_foods'],
  },
  {
    week: 22,
    trimester: 2,
    sizeKey: 'papaya',
    lengthCm: 27.8,
    weightG: 430,
    developmentKeys: ['grip_develops', 'eyebrows_visible', 'hearing_sharpens'],
    bodyKeys: ['braxton_hicks', 'breast_changes'],
    symptomKeys: ['swollen_ankles', 'hemorrhoids', 'insomnia'],
    tipKeys: ['rest_and_elevate_feet', 'fiber_rich_foods', 'sleep_on_side'],
  },
  {
    week: 23,
    trimester: 2,
    sizeKey: 'grapefruit',
    lengthCm: 28.9,
    weightG: 501,
    developmentKeys: ['lungs_prepare', 'responds_to_sound', 'skin_less_transparent'],
    bodyKeys: ['colostrum_may_appear', 'weight_gain_steady'],
    symptomKeys: ['swollen_ankles', 'back_ache', 'braxton_hicks_symptom'],
    tipKeys: ['glucose_test_soon', 'hydrate', 'antenatal_classes'],
  },
  {
    week: 24,
    trimester: 2,
    sizeKey: 'corn',
    lengthCm: 30,
    weightG: 600,
    developmentKeys: ['lungs_make_surfactant', 'inner_ear_complete', 'responds_to_sound'],
    bodyKeys: ['fundal_height_above_navel', 'braxton_hicks'],
    symptomKeys: ['heartburn', 'hip_pain', 'insomnia'],
    tipKeys: ['glucose_test', 'count_movements_daily', 'antenatal_classes'],
    milestoneKey: 'viability',
  },
  {
    week: 25,
    trimester: 2,
    sizeKey: 'cauliflower',
    lengthCm: 34.6,
    weightG: 660,
    developmentKeys: ['fat_under_skin', 'hair_gets_colour', 'responds_to_light'],
    bodyKeys: ['pelvis_loosens', 'sleep_harder'],
    symptomKeys: ['insomnia', 'hemorrhoids', 'restless_legs'],
    tipKeys: ['sleep_on_side', 'gentle_movement', 'birth_plan'],
  },
  {
    week: 26,
    trimester: 2,
    sizeKey: 'lettuce',
    lengthCm: 35.6,
    weightG: 760,
    developmentKeys: ['eyes_open', 'brain_waves_respond', 'practices_breathing'],
    bodyKeys: ['ribs_pressure', 'blood_pressure_watch'],
    symptomKeys: ['back_ache', 'shortness_breath', 'headaches'],
    tipKeys: ['monitor_blood_pressure', 'rest_and_elevate_feet', 'hydrate'],
  },
  {
    week: 27,
    trimester: 3,
    sizeKey: 'cabbage',
    lengthCm: 36.6,
    weightG: 875,
    developmentKeys: ['sleep_wake_cycles', 'yawning_hiccups', 'recognises_voices'],
    bodyKeys: ['braxton_hicks', 'ribs_pressure'],
    symptomKeys: ['leg_cramps', 'heartburn', 'braxton_hicks_symptom'],
    tipKeys: ['count_movements_daily', 'antenatal_classes', 'hospital_bag_list'],
    milestoneKey: 'third_trimester_start',
  },
  {
    week: 28,
    trimester: 3,
    sizeKey: 'eggplant',
    lengthCm: 37.6,
    weightG: 1005,
    developmentKeys: ['dreams_rem', 'blinking', 'rapid_weight_gain'],
    bodyKeys: ['antenatal_visits_increase', 'colostrum_may_appear'],
    symptomKeys: ['shortness_breath', 'back_ache', 'swollen_ankles'],
    tipKeys: ['blood_tests_check', 'count_movements_daily', 'sleep_on_side'],
  },
  {
    week: 29,
    trimester: 3,
    sizeKey: 'squash',
    lengthCm: 38.6,
    weightG: 1153,
    developmentKeys: ['bones_need_calcium', 'muscles_lungs_mature', 'brain_grows_fast'],
    bodyKeys: ['ribs_pressure', 'heartburn_more'],
    symptomKeys: ['heartburn', 'insomnia', 'frequent_urination'],
    tipKeys: ['calcium_rich_foods', 'small_frequent_meals', 'pelvic_floor_exercises'],
  },
  {
    week: 30,
    trimester: 3,
    sizeKey: 'cucumber',
    lengthCm: 39.9,
    weightG: 1319,
    developmentKeys: ['lanugo_disappears', 'marrow_makes_blood', 'coordinated_movements'],
    bodyKeys: ['fatigue_returns', 'balance_shifts'],
    symptomKeys: ['fatigue', 'back_ache', 'mood_swings'],
    tipKeys: ['rest_and_nap', 'birth_plan', 'breastfeeding_prep'],
  },
  {
    week: 31,
    trimester: 3,
    sizeKey: 'coconut',
    lengthCm: 41.1,
    weightG: 1502,
    developmentKeys: ['all_senses_working', 'rapid_weight_gain', 'kicks_stronger'],
    bodyKeys: ['braxton_hicks', 'less_room_lungs'],
    symptomKeys: ['braxton_hicks_symptom', 'shortness_breath', 'leg_cramps'],
    tipKeys: ['count_movements_daily', 'hospital_bag', 'pelvic_floor_exercises'],
  },
  {
    week: 32,
    trimester: 3,
    sizeKey: 'napa_cabbage',
    lengthCm: 42.4,
    weightG: 1702,
    developmentKeys: ['head_down_position', 'fingernails_reach_tips', 'practices_breathing'],
    bodyKeys: ['fundal_height_high', 'appetite_smaller'],
    symptomKeys: ['heartburn', 'pelvic_pressure', 'insomnia'],
    tipKeys: ['small_frequent_meals', 'hospital_bag', 'know_labour_signs'],
  },
  {
    week: 33,
    trimester: 3,
    sizeKey: 'pineapple',
    lengthCm: 43.7,
    weightG: 1918,
    developmentKeys: ['immune_transfer', 'skull_stays_soft', 'coordinated_movements'],
    bodyKeys: ['pelvis_loosens', 'swelling_common'],
    symptomKeys: ['swollen_ankles', 'carpal_tunnel', 'insomnia'],
    tipKeys: ['rest_and_elevate_feet', 'monitor_swelling', 'sleep_on_side'],
  },
  {
    week: 34,
    trimester: 3,
    sizeKey: 'cantaloupe',
    lengthCm: 45,
    weightG: 2146,
    developmentKeys: ['lungs_nearly_ready', 'vernix_thickens', 'eyes_focus'],
    bodyKeys: ['braxton_hicks', 'back_pressure'],
    symptomKeys: ['back_ache', 'pelvic_pressure', 'fatigue'],
    tipKeys: ['install_car_seat', 'birth_plan', 'antenatal_classes'],
  },
  {
    week: 35,
    trimester: 3,
    sizeKey: 'honeydew',
    lengthCm: 46.2,
    weightG: 2383,
    developmentKeys: ['rapid_weight_gain', 'kidneys_fully_developed', 'brain_grows_fast'],
    bodyKeys: ['less_room_movement', 'heartburn_more'],
    symptomKeys: ['shortness_breath', 'frequent_urination', 'insomnia'],
    tipKeys: ['group_b_strep_test', 'rest_and_nap', 'know_labour_signs'],
  },
  {
    week: 36,
    trimester: 3,
    sizeKey: 'romaine',
    lengthCm: 47.4,
    weightG: 2622,
    developmentKeys: ['skin_smooths', 'lanugo_disappears', 'gripping_strength'],
    bodyKeys: ['lightening_drop', 'cervix_softens'],
    symptomKeys: ['pelvic_pressure', 'frequent_urination', 'easier_breathing'],
    tipKeys: ['weekly_checkups', 'perineal_massage', 'plan_route_hospital'],
  },
  {
    week: 37,
    trimester: 3,
    sizeKey: 'chard',
    lengthCm: 48.6,
    weightG: 2859,
    developmentKeys: ['practices_breathing', 'meconium_builds', 'gripping_strength'],
    bodyKeys: ['mucus_plug', 'braxton_hicks'],
    symptomKeys: ['braxton_hicks_symptom', 'back_ache', 'nesting_energy'],
    tipKeys: ['know_labour_signs', 'hospital_bag', 'postpartum_support'],
    milestoneKey: 'early_term',
  },
  {
    week: 38,
    trimester: 3,
    sizeKey: 'leek',
    lengthCm: 49.8,
    weightG: 3083,
    developmentKeys: ['fat_layers_finish', 'gripping_strength', 'lungs_nearly_ready'],
    bodyKeys: ['cervix_softens', 'back_pressure'],
    symptomKeys: ['pelvic_pressure', 'swollen_ankles', 'insomnia'],
    tipKeys: ['rest_and_nap', 'count_movements_daily', 'breastfeeding_prep'],
  },
  {
    week: 39,
    trimester: 3,
    sizeKey: 'mini_watermelon',
    lengthCm: 50.7,
    weightG: 3288,
    developmentKeys: ['lungs_ready', 'immune_transfer', 'skin_smooths'],
    bodyKeys: ['mucus_plug', 'contractions_may_start'],
    symptomKeys: ['nesting_energy', 'pelvic_pressure', 'loose_stools'],
    tipKeys: ['know_labour_signs', 'plan_route_hospital', 'rest_and_nap'],
    milestoneKey: 'full_term',
  },
  {
    week: 40,
    trimester: 3,
    sizeKey: 'pumpkin',
    lengthCm: 51.2,
    weightG: 3462,
    developmentKeys: ['ready_for_birth', 'skull_stays_soft', 'coordinated_movements'],
    bodyKeys: ['contractions_may_start', 'cervix_dilates'],
    symptomKeys: ['contractions', 'back_ache', 'insomnia'],
    tipKeys: ['know_labour_signs', 'monitor_movements_closely', 'postpartum_support'],
    milestoneKey: 'due_date',
  },
];

export const TOTAL_WEEKS = WEEK_FACTS.length;

export function getWeekFacts(week: number): WeekFacts | undefined {
  return WEEK_FACTS.find((entry) => entry.week === week);
}
