import type { WeekPhrasebook } from './types';

export const deWeeks: WeekPhrasebook = {
  slugTemplate: 'woche-{n}',
  seoTitle: '{n}. SSW: Entwicklung, Anzeichen und Tipps',
  seoDescription:
    'In der {n}. Schwangerschaftswoche ist dein Baby etwa so groß wie {size}. Was sich diese Woche entwickelt, wie sich dein Körper verändert und worauf du achten solltest.',
  intro:
    'In der {n}. Schwangerschaftswoche ist dein Baby etwa so groß wie {size}. Du befindest dich im {trimester} — und diese Woche bringt ihre eigenen kleinen Veränderungen mit sich, für dein Baby und für dich.',
  trimesterInline: ['ersten Trimester', 'zweiten Trimester', 'dritten Trimester'],
  introEarly:
    'Woche {n} wird ab dem ersten Tag deiner letzten Periode gezählt und liegt damit vor der Empfängnis. Trotzdem zählt sie: Dein Körper schafft gerade die Bedingungen, die eine Schwangerschaft braucht.',
  expect: [
    'Die frühe Schwangerschaft ist von außen unsichtbar und innen sehr laut. Beschwerden kommen und gehen von Tag zu Tag — das ist normal. Noch {left} Wochen: Diese Woche zählen Ruhe, verträgliches Essen und der erste Termin bei Ärztin oder Hebamme.',
    'Die mittleren Monate sind meist die ruhigste Zeit der Schwangerschaft. Die Energie kommt zurück, der Bauch wird sichtbar, die Vorsorge wird zur Routine. Noch {left} Wochen: eine gute Zeit, um zu planen, solange du dich gut fühlst.',
    'Der letzte Abschnitt fordert deinen Körper. Der Schlaf wird schwieriger, die Bewegungen langsamer, die Termine häufiger. Noch {left} Wochen: Ruhe, die Anzeichen der Geburt kennen und die Kliniktasche bereitstellen.',
  ],
  sizes: {
    not_yet: 'noch nichts — die Empfängnis hat noch nicht stattgefunden',
    poppy_seed: 'ein Mohnkorn',
    sesame_seed: 'ein Sesamkorn',
    lentil: 'eine Linse',
    blueberry: 'eine Heidelbeere',
    raspberry: 'eine Himbeere',
    grape: 'eine Weintraube',
    kumquat: 'eine Kumquat',
    fig: 'eine Feige',
    lime: 'eine Limette',
    lemon: 'eine Zitrone',
    peach: 'ein Pfirsich',
    apple: 'ein Apfel',
    avocado: 'eine Avocado',
    pear: 'eine Birne',
    bell_pepper: 'eine Paprika',
    mango: 'eine Mango',
    banana: 'eine Banane',
    carrot: 'eine Karotte',
    papaya: 'eine Papaya',
    grapefruit: 'eine Grapefruit',
    corn: 'ein Maiskolben',
    cauliflower: 'ein Blumenkohl',
    lettuce: 'ein Kopfsalat',
    cabbage: 'ein Weißkohl',
    eggplant: 'eine Aubergine',
    squash: 'ein Butternusskürbis',
    cucumber: 'eine Salatgurke',
    coconut: 'eine Kokosnuss',
    napa_cabbage: 'ein Chinakohl',
    pineapple: 'eine Ananas',
    cantaloupe: 'eine Cantaloupe-Melone',
    honeydew: 'eine Honigmelone',
    romaine: 'ein Römersalat',
    chard: 'ein Bund Mangold',
    leek: 'eine Stange Lauch',
    mini_watermelon: 'eine kleine Wassermelone',
    pumpkin: 'ein kleiner Kürbis',
  },
  development: {
    prep_cycle: 'Noch gibt es kein Baby — dein Körper stößt die alte Schleimhaut ab und startet einen neuen Zyklus.',
    egg_released: 'Eine Eizelle reift im Follikel heran und ist bereit für den Eisprung.',
    ovulation: 'Der Eisprung findet etwa in der Zyklusmitte statt; die Eizelle ist rund 24 Stunden befruchtungsfähig.',
    fertilization: 'Trifft ein Spermium auf die Eizelle, findet die Befruchtung im Eileiter statt.',
    cell_division: 'Die einzelne Zelle teilt sich immer wieder, während sie zur Gebärmutter wandert.',
    implantation: 'Der Zellhaufen nistet sich in die Gebärmutterschleimhaut ein — die Einnistung.',
    placenta_begins: 'Die Zellen, aus denen die Plazenta wird, bilden sich und produzieren hCG.',
    three_layers_form: 'Drei Zellschichten entstehen; aus jeder wird ein anderer Teil deines Babys.',
    neural_tube_forms: 'Das Neuralrohr schließt sich und wird zu Gehirn und Rückenmark.',
    heart_begins_beating: 'Das winzige Herzrohr beginnt zu schlagen, zunächst nur als feines Flattern.',
    circulation_starts: 'Die ersten Blutgefäße bilden sich, der Kreislauf nimmt seine Arbeit auf.',
    arm_leg_buds: 'Kleine Knospen zeigen, wo Arme und Beine wachsen werden.',
    facial_features_form: 'Dunkle Punkte markieren die späteren Augen, der Kiefer nimmt Form an.',
    brain_grows_fast: 'Das Gehirn wächst rasant — etwa 100 neue Zellen pro Minute.',
    kidneys_form: 'Nieren, Leber und Lunge beginnen sich zu bilden.',
    fingers_toes_webbed: 'Finger und Zehen entstehen, noch durch feine Hautfalten verbunden.',
    tail_disappears: 'Der kleine embryonale Schwanz bildet sich in dieser Woche zurück.',
    spontaneous_movements: 'Dein Baby bewegt sich schon von selbst — viel zu zart, um es zu spüren.',
    all_organs_present: 'Alle wichtigen Organe sind angelegt, auch wenn keines fertig ist.',
    heartbeat_audible_scan: 'Der Herzschlag ist im Ultraschall meist sichtbar und hörbar.',
    muscles_develop: 'Muskeln entwickeln sich, winzige Gelenke beginnen sich zu beugen.',
    embryo_becomes_fetus: 'Dein Baby heißt jetzt Fetus — die kritische Phase der Organbildung ist abgeschlossen.',
    fingernails_start: 'An Fingern und Zehen entstehen die Nagelbetten.',
    bones_hardening: 'Weicher Knorpel verknöchert langsam.',
    fingers_toes_separate: 'Finger und Zehen sind getrennt, die Nägel beginnen zu wachsen.',
    tooth_buds_form: 'Im Kiefer bilden sich die Zahnknospen — für viele Jahre später.',
    reflexes_begin: 'Erste Reflexe: Dein Baby krümmt Finger und Zehen und öffnet den Mund.',
    kidneys_make_urine: 'Die Nieren produzieren Urin, der Teil des Fruchtwassers wird.',
    vocal_cords_form: 'Die Stimmbänder entstehen, auch wenn Schall Luft zum Klingen braucht.',
    fingerprints_form: 'An den Fingerkuppen bilden sich einzigartige Fingerabdrücke.',
    external_genitals_form: 'Die äußeren Geschlechtsorgane entwickeln sich und werden später sichtbar.',
    facial_expressions: 'Die Gesichtsmuskeln arbeiten — dein Baby kann blinzeln und die Stirn runzeln.',
    lanugo_appears: 'Ein feiner Flaum, die Lanugobehaarung, überzieht die Haut.',
    sucking_reflex: 'Der Saugreflex entsteht; vielleicht findet dein Baby seinen Daumen.',
    hearing_begins: 'Die Knochen des Innenohrs verhärten, erste Geräusche dringen durch.',
    taste_buds_form: 'Geschmacksknospen entstehen und nehmen Aromen im Fruchtwasser wahr.',
    coordinated_movements: 'Die Bewegungen werden weicher und koordinierter.',
    hears_your_voice: 'Dein Baby hört deine Stimme, deinen Herzschlag und deine Verdauung.',
    eyes_move_slowly: 'Die Augen bewegen sich langsam hinter geschlossenen Lidern.',
    fat_under_skin: 'Braunes Fettgewebe entsteht unter der Haut — Wärmeschutz für nach der Geburt.',
    umbilical_cord_thickens: 'Die Nabelschnur wird dicker und stabiler.',
    sweat_glands_form: 'Unter der entstehenden Haut bilden sich Schweißdrüsen.',
    hearing_sharpens: 'Das Gehör wird schärfer; laute Geräusche lassen dein Baby zusammenzucken.',
    myelin_forms: 'Eine Schutzschicht namens Myelin beginnt, die Nerven zu umhüllen.',
    yawning_hiccups: 'Dein Baby gähnt, hat Schluckauf und streckt sich im Fruchtwasser.',
    vernix_forms: 'Eine wachsartige Schicht, die Käseschmiere, schützt die Haut.',
    brain_maps_senses: 'Im Gehirn entstehen Areale für Geruch, Geschmack, Hören, Sehen und Fühlen.',
    hair_on_head: 'Auf dem Kopf beginnen Haare zu wachsen.',
    swallowing_practice: 'Dein Baby schluckt Fruchtwasser und übt so das Trinken.',
    rapid_weight_gain: 'Die Gewichtszunahme beschleunigt sich ab jetzt deutlich.',
    taste_through_fluid: 'Was du isst, würzt das Fruchtwasser — dein Baby schmeckt mit.',
    marrow_makes_blood: 'Das Knochenmark übernimmt die Bildung roter Blutkörperchen.',
    grip_develops: 'Dein Baby greift nach der Nabelschnur und ertastet seine Umgebung.',
    eyebrows_visible: 'Augenbrauen und Wimpern sind jetzt zu erkennen.',
    lungs_prepare: 'In der Lunge entstehen die feinen Verästelungen für die spätere Atmung.',
    responds_to_sound: 'Vertraute Stimmen und Musik können dein Baby bewegen oder beruhigen.',
    skin_less_transparent: 'Die Haut wird durch Pigmente weniger durchscheinend.',
    lungs_make_surfactant: 'Die Lunge bildet Surfactant, das sie nach der Geburt offen hält.',
    inner_ear_complete: 'Das Innenohr ist fertig — es hilft auch beim Gleichgewicht.',
    hair_gets_colour: 'Die Haare bekommen langsam Farbe.',
    responds_to_light: 'Helles Licht auf dem Bauch lässt dein Baby sich abwenden.',
    eyes_open: 'Die Augenlider öffnen sich zum ersten Mal.',
    brain_waves_respond: 'Die Hirnströme reagieren jetzt auf Geräusche und Berührung.',
    practices_breathing: 'Dein Baby übt Atembewegungen mit Fruchtwasser.',
    sleep_wake_cycles: 'Klare Schlaf- und Wachphasen entstehen — oft andere als deine.',
    recognises_voices: 'Dein Baby erkennt deine Stimme und wird ruhiger, wenn du sprichst.',
    dreams_rem: 'Der REM-Schlaf beginnt — die Phase, die mit Träumen verbunden ist.',
    blinking: 'Dein Baby kann blinzeln, die Wimpern sind vollständig.',
    bones_need_calcium: 'Die Knochen härten schnell und holen sich Kalzium aus deiner Ernährung.',
    muscles_lungs_mature: 'Muskeln und Lunge reifen stetig weiter.',
    lanugo_disappears: 'Der feine Lanugoflaum verschwindet allmählich.',
    all_senses_working: 'Alle fünf Sinne arbeiten jetzt.',
    kicks_stronger: 'Die Tritte fühlen sich kräftiger an, weil der Platz enger wird.',
    head_down_position: 'Viele Babys drehen sich jetzt in Kopflage — Platz zum Drehen ist noch da.',
    fingernails_reach_tips: 'Die Fingernägel reichen bis zu den Fingerkuppen.',
    immune_transfer: 'Antikörper gehen von dir auf dein Baby über und bauen den ersten Immunschutz auf.',
    skull_stays_soft: 'Die Schädelknochen bleiben weich und beweglich, damit der Kopf durch den Geburtskanal passt.',
    lungs_nearly_ready: 'Die Lunge ist fast bereit, Luft zu atmen.',
    vernix_thickens: 'Die Käseschmiere wird dicker und schützt die Haut.',
    eyes_focus: 'Dein Baby kann Nahes fokussieren und Licht folgen.',
    kidneys_fully_developed: 'Die Nieren sind vollständig entwickelt, die Leber verarbeitet erste Abbaustoffe.',
    skin_smooths: 'Fettpolster füllen die Haut, die Fältchen glätten sich.',
    gripping_strength: 'Der Griff ist kräftig genug, um nach der Geburt deinen Finger zu halten.',
    meconium_builds: 'Im Darm sammelt sich Mekonium, der erste dunkle Stuhl.',
    fat_layers_finish: 'Die letzten Fettschichten entstehen und helfen später bei der Wärmeregulierung.',
    lungs_ready: 'Die Lunge ist bereit, Gehirn und Nervensystem reifen weiter.',
    ready_for_birth: 'Dein Baby ist bereit — es wächst bis zur Geburt weiter.',
  },
  body: {
    period_starts: 'Deine Periode markiert Tag eins — von hier an werden die Schwangerschaftswochen gezählt.',
    uterus_lining_sheds: 'Die Gebärmutterschleimhaut löst sich, eine neue baut sich auf.',
    fertile_window: 'Du befindest dich in den fruchtbarsten Tagen des Zyklus.',
    cervical_mucus_changes: 'Der Zervixschleim wird um den Eisprung klar und spinnbar.',
    hormones_rising: 'Die Hormonwerte steigen stetig und stützen die frühe Schwangerschaft.',
    uterus_lining_thickens: 'Die Gebärmutterschleimhaut wird dicker und bereitet die Einnistung vor.',
    hcg_detectable: 'hCG wird nachweisbar — genau das misst ein Schwangerschaftstest.',
    missed_period_soon: 'Deine Periode wäre jetzt fällig; ihr Ausbleiben ist oft das erste Zeichen.',
    blood_volume_rises: 'Dein Blutvolumen steigt weiter, um die Plazenta zu versorgen.',
    uterus_grows_slightly: 'Die Gebärmutter wächst, von außen ist davon noch nichts zu sehen.',
    breast_changes: 'Die Brüste fühlen sich voller an, die Warzenhöfe können dunkler werden.',
    mucus_plug_forms: 'Im Gebärmutterhals bildet sich der Schleimpfropf und verschließt die Gebärmutter.',
    uterus_size_orange: 'Deine Gebärmutter hat etwa die Größe einer großen Orange.',
    skin_changes_body: 'Die stärkere Durchblutung lässt die Haut strahlen — oder unreiner werden.',
    waist_thickens: 'Der Hosenbund kneift, noch bevor ein Bauch zu sehen ist.',
    uterus_rises_pelvis: 'Die Gebärmutter steigt aus dem Becken und ist tief zu ertasten.',
    nausea_may_ease: 'Bei vielen Frauen lässt die Übelkeit jetzt nach.',
    energy_returns: 'Die Energie kehrt zurück, wenn sich die Hormone einpendeln.',
    showing_starts: 'Ein kleiner Bauch wird sichtbar, besonders abends.',
    uterus_grows_steadily: 'Die Gebärmutter wächst ab jetzt etwa einen Zentimeter pro Woche.',
    nasal_membranes_swell: 'Die stärkere Durchblutung lässt die Nasenschleimhäute anschwellen.',
    fundal_height_navel: 'Die Gebärmutter steht etwa auf halbem Weg zum Bauchnabel.',
    ligaments_soften: 'Bänder werden weicher und dehnbarer, um Platz zu schaffen.',
    balance_shifts: 'Dein Schwerpunkt verlagert sich, Bewegungen fühlen sich anders an.',
    first_movements: 'Die ersten Bewegungen spürst du meist zwischen der 18. und 22. Woche.',
    appetite_grows: 'Der Appetit wächst, weil dein Baby schneller zunimmt.',
    skin_pigment_changes: 'Pigmentveränderungen sind häufig: eine dunkle Linie am Bauch, dunklere Flecken im Gesicht.',
    uterus_at_navel: 'Die Gebärmutter erreicht den Bauchnabel — die klassische Marke der 20. Woche.',
    weight_gain_steady: 'Die Gewichtszunahme wird gleichmäßig, meist ein paar hundert Gramm pro Woche.',
    braxton_hicks: 'Erste Übungswehen können auftreten — sie sind keine Geburtswehen.',
    colostrum_may_appear: 'Aus der Brust können einzelne Tropfen Kolostrum austreten.',
    fundal_height_above_navel: 'Die Gebärmutter steht einige Zentimeter über dem Bauchnabel.',
    pelvis_loosens: 'Das Becken wird durch Relaxin lockerer.',
    sleep_harder: 'Bequeme Schlafpositionen werden schwerer zu finden.',
    ribs_pressure: 'Die wachsende Gebärmutter drückt nach oben gegen die Rippen.',
    blood_pressure_watch: 'Blutdruck und Urin werden bei jedem Termin auf Präeklampsie-Zeichen geprüft.',
    antenatal_visits_increase: 'Die Vorsorgetermine finden ab jetzt meist häufiger statt.',
    heartburn_more: 'Der Magen hat weniger Platz, Sodbrennen tritt häufiger auf.',
    fatigue_returns: 'Die Müdigkeit des dritten Trimesters kommt zurück, oft ganz plötzlich.',
    less_room_lungs: 'Die Lunge hat weniger Platz, tiefes Atmen fällt schwerer.',
    fundal_height_high: 'Die Gebärmutter steht hoch, direkt unter den Rippen.',
    appetite_smaller: 'Kleinere Mahlzeiten tun gut — für einen vollen Magen ist kaum Platz.',
    swelling_common: 'Leichte Schwellungen an Händen, Füßen und Knöcheln sind normal.',
    back_pressure: 'Das Gewicht vorn belastet den unteren Rücken dauerhaft.',
    less_room_movement: 'Die Bewegungen fühlen sich eher wie Rollen und Schieben an als wie Tritte.',
    lightening_drop: 'Das Baby rutscht tiefer ins Becken — der sogenannte Senkbauch.',
    cervix_softens: 'Der Muttermund wird weicher und beginnt sich zu verkürzen.',
    mucus_plug: 'Der Schleimpfropf kann Tage oder Stunden vor der Geburt abgehen.',
    contractions_may_start: 'Die Wehen können jetzt jederzeit einsetzen.',
    cervix_dilates: 'Sobald die Geburt beginnt, öffnet sich der Muttermund.',
  },
  symptoms: {
    period_symptoms: 'Normale Periodenbeschwerden — Krämpfe und ein schweres, müdes Gefühl',
    fatigue: 'Tiefe Müdigkeit, selbst nach einer vollen Nacht Schlaf',
    mood_swings: 'Schnell wechselnde Stimmungen, hormonell bedingt',
    ovulation_signs: 'Ein Ziehen auf einer Seite und klarer, spinnbarer Ausfluss',
    breast_tenderness: 'Empfindliche, schwerere Brüste',
    increased_appetite: 'Deutlich größerer Appetit',
    no_symptoms_yet: 'Meist noch gar nichts — für Anzeichen ist es viel zu früh',
    bloating: 'Blähbauch und ein enges, volles Gefühl',
    light_spotting: 'Leichte Schmierblutung, möglicherweise die Einnistungsblutung',
    nausea: 'Übelkeit, die zu jeder Tageszeit kommen kann',
    frequent_urination: 'Häufigerer Harndrang',
    heightened_smell: 'Ein schärferer Geruchssinn, der Vertrautes unangenehm macht',
    food_aversions: 'Starke Abneigungen und Gelüste beim Essen',
    headaches: 'Kopfschmerzen, oft hormonell oder durch zu wenig Flüssigkeit',
    constipation: 'Verstopfung, weil die Verdauung langsamer wird',
    heartburn: 'Sodbrennen und saures Aufstoßen, besonders nach dem Essen',
    nausea_easing: 'Übelkeit, die endlich nachlässt',
    dizziness: 'Schwindel beim zu schnellen Aufstehen',
    nasal_congestion: 'Eine verstopfte Nase ganz ohne Erkältung',
    round_ligament_pain: 'Kurzes, stechendes Ziehen im Unterbauch beim Bewegen',
    forgetfulness: 'Vergesslichkeit und Konzentrationsprobleme',
    skin_changes: 'Hautveränderungen: dunklere Flecken, eine Linie am Bauch oder Unreinheiten',
    nosebleeds: 'Gelegentliches Nasenbluten und empfindliches Zahnfleisch',
    leg_cramps: 'Wadenkrämpfe, meist nachts',
    back_ache: 'Ein dumpfer Schmerz im unteren Rücken',
    vivid_dreams: 'Ungewöhnlich lebhafte Träume',
    swollen_ankles: 'Geschwollene Füße und Knöchel am Abend',
    hip_pain: 'Schmerzende Hüften, besonders im Seitenschlaf',
    shortness_breath: 'Schnellere Kurzatmigkeit',
    discharge_increase: 'Mehr Ausfluss, dünn und milchig weiß',
    stretch_marks_itch: 'Juckende, gespannte Haut am Bauch',
    varicose_veins: 'Krampfadern an den Beinen',
    hemorrhoids: 'Hämorrhoiden, verstärkt durch Verstopfung',
    insomnia: 'Unterbrochener Schlaf und Schwierigkeiten, bequem zu liegen',
    braxton_hicks_symptom: 'Schmerzloses Hartwerden des Bauchs, das kommt und geht',
    restless_legs: 'Unruhige Beine am Abend',
    pelvic_pressure: 'Starker Druck tief im Becken',
    carpal_tunnel: 'Kribbelnde oder taube Finger, vor allem morgens',
    easier_breathing: 'Leichteres Atmen, sobald das Baby tiefer rutscht',
    nesting_energy: 'Plötzlicher Drang, alles zu putzen und vorzubereiten',
    loose_stools: 'Weicherer Stuhl, der der Geburt vorausgehen kann',
    contractions: 'Wehen, die länger, stärker und regelmäßiger werden',
  },
  tips: {
    start_folic_acid: 'Nimm täglich 400 µg Folsäure — sie schützt das Neuralrohr, bevor du überhaupt von der Schwangerschaft weißt.',
    track_cycle: 'Beobachte deinen Zyklus: So kennst du deine fruchtbaren Tage und die Terminbestimmung wird genauer.',
    avoid_alcohol_smoking: 'Verzichte auf Alkohol und Zigaretten und lass Medikamente ärztlich prüfen.',
    gentle_movement: 'Bleib sanft in Bewegung — ein täglicher Spaziergang hilft Kreislauf, Stimmung und Schlaf.',
    prenatal_vitamin: 'Nimm ein Schwangerschaftsvitamin mit Folsäure und Vitamin D.',
    hydrate: 'Trink über den Tag verteilt Wasser; Flüssigkeitsmangel verstärkt Müdigkeit und Kopfschmerzen.',
    take_test: 'Ein Test zu Hause ist ab dem Tag der erwarteten Periode am zuverlässigsten.',
    book_first_appointment: 'Vereinbare den ersten Vorsorgetermin — meist zwischen Woche 8 und 12.',
    small_frequent_meals: 'Iss kleine Portionen über den Tag; ein leerer Magen verstärkt Übelkeit.',
    rest_when_tired: 'Ruh dich ohne schlechtes Gewissen aus. Die Müdigkeit im ersten Trimester ist echt und vorübergehend.',
    first_scan_booking: 'Plane den Ersttrimester-Ultraschall, üblich zwischen Woche 10 und 14.',
    talk_about_worries: 'Sprich mit jemandem, dem du vertraust, über deine Gefühle — Sorgen gehören dazu.',
    fiber_rich_foods: 'Iss ballaststoffreich — Gemüse, Haferflocken, Hülsenfrüchte — damit die Verdauung in Gang bleibt.',
    first_trimester_screening: 'Besprich die Möglichkeiten des Ersttrimester-Screenings mit deiner Ärztin oder Hebamme.',
    iron_rich_foods: 'Kombiniere eisenreiche Lebensmittel mit Vitamin C, das verbessert die Aufnahme.',
    tell_employer: 'Überlege, wann du deinem Arbeitgeber Bescheid gibst, und prüfe deine Rechte im Mutterschutz.',
    sleep_on_side: 'Gewöhn dich ans Schlafen auf der Seite, am besten links.',
    maternity_clothes: 'Wechsle rechtzeitig zu weichen Bündchen, bevor die Kleidung drückt.',
    moisturise_skin: 'Creme den Bauch täglich ein — Dehnungsstreifen verhindert das nicht, aber es lindert den Juckreiz.',
    pelvic_floor_exercises: 'Trainiere täglich den Beckenboden; das hilft jetzt und nach der Geburt.',
    talk_and_sing: 'Sprich, lies oder sing für deinen Bauch — dein Baby beginnt zu hören.',
    anomaly_scan_booking: 'Vereinbare den großen Organultraschall, üblich zwischen Woche 18 und 22.',
    supportive_shoes: 'Trag stabile Schuhe; gelockerte Bänder machen die Knöchel unsicherer.',
    anomaly_scan: 'Beim Organultraschall werden Organe, Wachstum und Plazenta genau untersucht.',
    rest_and_elevate_feet: 'Leg die Beine hoch, wann immer es geht, das lindert Schwellungen.',
    sun_protection: 'Nutze Sonnenschutz — die Haut pigmentiert in der Schwangerschaft schneller.',
    start_kick_awareness: 'Achte darauf, wann und wie sich dein Baby bewegt.',
    birth_plan: 'Denk über deine Geburtswünsche nach und darüber, wo du entbinden möchtest.',
    glucose_test_soon: 'Der Zuckerbelastungstest steht bald an, meist zwischen Woche 24 und 28.',
    antenatal_classes: 'Melde dich zum Geburtsvorbereitungskurs an — gute Kurse sind früh ausgebucht.',
    glucose_test: 'Nimm den Glukosetoleranztest wahr, wenn er dir angeboten wird.',
    count_movements_daily: 'Lern das tägliche Bewegungsmuster deines Babys kennen und melde dich bei Veränderungen.',
    monitor_blood_pressure: 'Melde Kopfschmerzen, Sehstörungen oder plötzliche Schwellungen sofort.',
    hospital_bag_list: 'Beginne eine Liste für die Kliniktasche — packen musst du noch nicht.',
    blood_tests_check: 'Jetzt wird das Blut auf Blutarmut geprüft; bei Rhesus-negativem Blut wird Anti-D angeboten.',
    calcium_rich_foods: 'Iss kalziumreich — die Knochen deines Babys härten gerade schnell.',
    rest_and_nap: 'Mach kurze Nickerchen, wenn die Nächte unruhig sind; die Müdigkeit summiert sich.',
    breastfeeding_prep: 'Informier dich über das Stillen und über Alternativen, damit die ersten Tage vertrauter wirken.',
    hospital_bag: 'Pack die Kliniktasche, damit sie ab Woche 36 bereitsteht.',
    know_labour_signs: 'Kenne die Anzeichen der Geburt: regelmäßige Wehen, Blasensprung, Blutung.',
    monitor_swelling: 'Plötzliche Schwellungen im Gesicht oder an den Händen gehören am selben Tag abgeklärt.',
    install_car_seat: 'Baue die Babyschale ein und probiere sie aus, solange keine Eile herrscht.',
    group_b_strep_test: 'Frag nach dem Test auf B-Streptokokken, wo er angeboten wird.',
    weekly_checkups: 'Die Vorsorgetermine finden ab jetzt meist wöchentlich statt.',
    perineal_massage: 'Dammmassage ab Woche 34 kann Geburtsverletzungen verringern.',
    plan_route_hospital: 'Plane den Weg in die Klinik und eine Alternative, falls dein Fahrer ausfällt.',
    postpartum_support: 'Organisiere Hilfe für die ersten zwei Wochen zu Hause — Essen, Wäsche, Gesellschaft.',
    monitor_movements_closely: 'Weniger Bewegungen gehören immer abgeklärt, auch nach dem Termin.',
  },
  milestones: {
    implantation_milestone: 'Ein Schwangerschaftstest kann diese Woche positiv werden.',
    fetus_milestone: 'Dein Baby heißt jetzt offiziell Fetus.',
    first_trimester_end: 'Ende des ersten Trimesters — das Fehlgeburtsrisiko sinkt deutlich.',
    second_trimester_start: 'Willkommen im zweiten Trimester.',
    halfway: 'Die Hälfte ist geschafft.',
    viability: 'Ab dieser Woche haben früh geborene Babys mit intensivmedizinischer Betreuung echte Überlebenschancen.',
    third_trimester_start: 'Das dritte Trimester beginnt.',
    early_term: 'Deine Schwangerschaft gilt jetzt als frühe Termingeburt.',
    full_term: 'Dein Baby ist reif für die Geburt.',
    due_date: 'Das ist deine Terminwoche — nur etwa jedes zwanzigste Baby kommt genau am errechneten Tag.',
  },
  faq: [
    {
      question: 'Der wievielte Monat ist die {n}. SSW?',
      answer: 'Die {n}. Schwangerschaftswoche entspricht {months}. Monate lassen sich nicht sauber in Wochen aufteilen, deshalb ist das Zählen in Wochen genauer.',
    },
    {
      question: 'Wie groß ist mein Baby in der {n}. SSW?',
      answer: 'In der {n}. Woche ist dein Baby etwa so groß wie {size} — rund {length} lang und ungefähr {weight} schwer. Gesunde Babys weichen deutlich von diesen Durchschnittswerten ab.',
    },
    {
      question: 'Welche Beschwerden sind in der {n}. SSW normal?',
      answer: 'Die häufigsten Anzeichen dieser Woche findest du oben. Melde dich sofort bei starker Blutung, heftigen Schmerzen, Fieber oder wenn sich die Bewegungen deines Babys verändern.',
    },
  ],
  monthsLabel: 'etwa {months} Monate',
};
