import type { WeekPhrasebook } from './types';

export const enWeeks: WeekPhrasebook = {
  slugTemplate: 'week-{n}',
  seoTitle: '{n} Weeks Pregnant: Baby Development, Symptoms & Tips',
  seoDescription:
    'At {n} weeks pregnant your baby is about the size of {size}. See what is developing this week, how your body changes, common symptoms and what to expect.',
  intro:
    'At {n} weeks pregnant your baby is about the size of {size}. You are in the {trimester}, and this week brings its own small changes — for your baby and for you.',
  trimesterInline: ['first trimester', 'second trimester', 'third trimester'],
  introEarly:
    'Week {n} is counted from the first day of your last period, so it happens before there is an embryo. It still matters: your body is preparing the conditions a pregnancy needs.',
  expect: [
    'Early pregnancy can feel invisible from the outside and very loud on the inside. Symptoms come and go from day to day, and that is normal. With {left} weeks to go, the priority this week is rest, gentle food and your first antenatal appointment.',
    'The middle months are usually the steadiest part of pregnancy. Energy often returns, the bump becomes visible, and appointments settle into a routine. With {left} weeks to go, this is a good time to plan ahead while you feel well.',
    'The last stretch asks a lot of your body. Sleep gets harder, movement slows down, and your appointments become more frequent. With {left} weeks to go, focus on rest, on knowing the signs of labour, and on having your bag ready.',
  ],
  sizes: {
    not_yet: 'nothing yet — conception has not happened',
    poppy_seed: 'a poppy seed',
    sesame_seed: 'a sesame seed',
    lentil: 'a lentil',
    blueberry: 'a blueberry',
    raspberry: 'a raspberry',
    grape: 'a grape',
    kumquat: 'a kumquat',
    fig: 'a fig',
    lime: 'a lime',
    lemon: 'a lemon',
    peach: 'a peach',
    apple: 'an apple',
    avocado: 'an avocado',
    pear: 'a pear',
    bell_pepper: 'a bell pepper',
    mango: 'a mango',
    banana: 'a banana',
    carrot: 'a carrot',
    papaya: 'a papaya',
    grapefruit: 'a grapefruit',
    corn: 'an ear of corn',
    cauliflower: 'a cauliflower',
    lettuce: 'a head of lettuce',
    cabbage: 'a cabbage',
    eggplant: 'an aubergine',
    squash: 'a butternut squash',
    cucumber: 'a cucumber',
    coconut: 'a coconut',
    napa_cabbage: 'a napa cabbage',
    pineapple: 'a pineapple',
    cantaloupe: 'a cantaloupe melon',
    honeydew: 'a honeydew melon',
    romaine: 'a romaine lettuce',
    chard: 'a bunch of chard',
    leek: 'a leek',
    mini_watermelon: 'a small watermelon',
    pumpkin: 'a small pumpkin',
  },
  development: {
    prep_cycle: 'There is no baby yet — your body is shedding the old lining and starting a fresh cycle.',
    egg_released: 'One egg finishes maturing inside its follicle, ready to be released.',
    ovulation: 'Ovulation happens around the middle of the cycle; the egg can be fertilised for about 24 hours.',
    fertilization: 'If sperm meets egg, fertilisation takes place in the fallopian tube.',
    cell_division: 'The single cell divides again and again as it travels towards the uterus.',
    implantation: 'The ball of cells settles into the lining of your uterus — this is implantation.',
    placenta_begins: 'The cells that will become the placenta begin to form and produce hCG.',
    three_layers_form: 'Three layers of cells appear; each will become a different part of your baby.',
    neural_tube_forms: 'The neural tube closes and becomes the brain and spinal cord.',
    heart_begins_beating: 'The tiny heart tube starts to beat, at first as a simple flutter.',
    circulation_starts: 'The first blood vessels form and circulation begins.',
    arm_leg_buds: 'Small buds appear where the arms and legs will grow.',
    facial_features_form: 'Dark spots mark where the eyes will be, and the jaw begins to take shape.',
    brain_grows_fast: 'The brain is growing quickly — around 100 new cells every minute.',
    kidneys_form: 'The kidneys, liver and lungs are all beginning to form.',
    fingers_toes_webbed: 'Fingers and toes are forming, still joined by thin webs of skin.',
    tail_disappears: 'The small embryonic tail disappears this week.',
    spontaneous_movements: 'Your baby moves spontaneously, far too gently for you to feel.',
    all_organs_present: 'Every major organ is now present, though none is finished.',
    heartbeat_audible_scan: 'The heartbeat can usually be seen and heard on an early scan.',
    muscles_develop: 'Muscles are developing, and tiny joints start to bend.',
    embryo_becomes_fetus: 'Your baby is now called a fetus — the critical organ-building stage is complete.',
    fingernails_start: 'Nail beds appear on fingers and toes.',
    bones_hardening: 'Soft cartilage is slowly hardening into bone.',
    fingers_toes_separate: 'Fingers and toes have separated, and nails begin to grow.',
    tooth_buds_form: 'Tooth buds form in the gums, ready for years from now.',
    reflexes_begin: 'Reflexes begin: your baby can curl fingers and toes and open the mouth.',
    kidneys_make_urine: 'The kidneys start producing urine, which becomes part of the amniotic fluid.',
    vocal_cords_form: 'Vocal cords take shape, although sound needs air to travel.',
    fingerprints_form: 'Unique fingerprints form on the tips of the fingers.',
    external_genitals_form: 'The external genitals are forming and may be visible on a later scan.',
    facial_expressions: 'Facial muscles start to work — your baby can squint and frown.',
    lanugo_appears: 'Fine, soft hair called lanugo begins to cover the skin.',
    sucking_reflex: 'The sucking reflex appears; your baby may find a thumb.',
    hearing_begins: 'The bones of the inner ear harden, and the first sounds get through.',
    taste_buds_form: 'Taste buds form and can pick up flavours in the amniotic fluid.',
    coordinated_movements: 'Movements become smoother and more coordinated.',
    hears_your_voice: 'Your baby can hear your voice, your heartbeat and your digestion.',
    eyes_move_slowly: 'The eyes move slowly behind closed lids.',
    fat_under_skin: 'Brown fat starts to build under the skin to help keep warm after birth.',
    umbilical_cord_thickens: 'The umbilical cord grows thicker and stronger.',
    sweat_glands_form: 'Sweat glands develop under the forming skin.',
    hearing_sharpens: 'Hearing sharpens; loud sounds may make your baby startle.',
    myelin_forms: 'A protective layer called myelin begins to coat the nerves.',
    yawning_hiccups: 'Your baby yawns, hiccups and stretches inside the amniotic fluid.',
    vernix_forms: 'A waxy coating called vernix protects the skin from the fluid.',
    brain_maps_senses: 'The brain is mapping areas for smell, taste, hearing, sight and touch.',
    hair_on_head: 'Hair starts to grow on the scalp.',
    swallowing_practice: 'Your baby swallows amniotic fluid, practising for feeding.',
    rapid_weight_gain: 'Weight gain speeds up noticeably from now on.',
    taste_through_fluid: 'What you eat flavours the amniotic fluid, and your baby tastes it.',
    marrow_makes_blood: 'Bone marrow takes over making red blood cells.',
    grip_develops: 'Your baby can grip the umbilical cord and touch the surroundings.',
    eyebrows_visible: 'Eyebrows and eyelashes are now visible.',
    lungs_prepare: 'The lungs form the tiny branches that will one day carry air.',
    responds_to_sound: 'Familiar voices and music can make your baby move or settle.',
    skin_less_transparent: 'The skin is less transparent as pigment develops.',
    lungs_make_surfactant: 'The lungs begin producing surfactant, which keeps them open after birth.',
    inner_ear_complete: 'The inner ear is complete, which also helps with balance.',
    hair_gets_colour: 'Hair begins to take on colour.',
    responds_to_light: 'A bright light on your bump may make your baby turn away.',
    eyes_open: 'The eyelids open for the first time.',
    brain_waves_respond: 'Brain waves now respond to sound and touch.',
    practices_breathing: 'Your baby practises breathing movements with amniotic fluid.',
    sleep_wake_cycles: 'Clear sleep and wake cycles appear, often different from yours.',
    recognises_voices: 'Your baby recognises your voice and may calm when you speak.',
    dreams_rem: 'Rapid eye movement sleep begins — the stage linked with dreaming.',
    blinking: 'Your baby can blink, and eyelashes are fully grown.',
    bones_need_calcium: 'Bones are hardening fast and drawing calcium from your diet.',
    muscles_lungs_mature: 'Muscles and lungs continue to mature steadily.',
    lanugo_disappears: 'The fine lanugo hair starts to disappear.',
    all_senses_working: 'All five senses are working now.',
    kicks_stronger: 'Kicks feel stronger and sharper as space gets tighter.',
    head_down_position: 'Many babies settle head-down around this time — there is still room to turn.',
    fingernails_reach_tips: 'Fingernails reach the tips of the fingers.',
    immune_transfer: 'Antibodies pass from you to your baby, building early immunity.',
    skull_stays_soft: 'The skull bones stay soft and separate so the head can pass through the birth canal.',
    lungs_nearly_ready: 'The lungs are nearly ready to breathe air.',
    vernix_thickens: 'The vernix coating thickens to protect the skin.',
    eyes_focus: 'Your baby can focus on close objects and follow light.',
    kidneys_fully_developed: 'The kidneys are fully developed and the liver processes some waste.',
    skin_smooths: 'Fat fills out the skin and the wrinkles smooth away.',
    gripping_strength: 'The grip is firm enough to hold your finger after birth.',
    meconium_builds: 'Meconium, the first dark stool, collects in the bowel.',
    fat_layers_finish: 'The last layers of fat go on, helping temperature control after birth.',
    lungs_ready: 'The lungs are ready, and the brain and nervous system keep maturing.',
    ready_for_birth: 'Your baby is ready to be born — growth continues right up to labour.',
  },
  body: {
    period_starts: 'Your period marks day one, and pregnancy weeks are counted from here.',
    uterus_lining_sheds: 'The uterine lining sheds and a new one starts to build.',
    fertile_window: 'You are in the most fertile days of the cycle.',
    cervical_mucus_changes: 'Cervical mucus becomes clear and stretchy around ovulation.',
    hormones_rising: 'Hormone levels rise steadily to support the early pregnancy.',
    uterus_lining_thickens: 'The lining of the uterus thickens, ready for implantation.',
    hcg_detectable: 'hCG becomes detectable, which is what a pregnancy test measures.',
    missed_period_soon: 'Your period is due about now — a missed period is often the first sign.',
    blood_volume_rises: 'Your blood volume keeps rising to supply the placenta.',
    uterus_grows_slightly: 'The uterus is growing, though nothing shows from the outside yet.',
    breast_changes: 'Breasts feel fuller and the areolas may darken.',
    mucus_plug_forms: 'A mucus plug forms in the cervix and seals the uterus.',
    uterus_size_orange: 'Your uterus is roughly the size of a large orange.',
    skin_changes_body: 'Higher blood flow can leave your skin brighter — or spottier.',
    waist_thickens: 'Your waistband may start to feel tight before any bump shows.',
    uterus_rises_pelvis: 'The uterus rises out of the pelvis and can be felt low down.',
    nausea_may_ease: 'For many women, nausea starts to ease around now.',
    energy_returns: 'Energy often returns as first-trimester hormones settle.',
    showing_starts: 'A small bump becomes visible, especially by the end of the day.',
    uterus_grows_steadily: 'The uterus grows about a centimetre a week from here.',
    nasal_membranes_swell: 'Extra blood flow swells the membranes in your nose.',
    fundal_height_navel: 'The top of the uterus is now roughly halfway to your navel.',
    ligaments_soften: 'Ligaments soften and stretch to make room.',
    balance_shifts: 'Your centre of gravity shifts, so movements feel different.',
    first_movements: 'First flutters — quickening — are often felt between weeks 18 and 22.',
    appetite_grows: 'Appetite grows as your baby gains weight faster.',
    skin_pigment_changes: 'Pigment changes are common: a dark line on the belly, darker patches on the face.',
    uterus_at_navel: 'The top of the uterus reaches your navel — a classic week-20 landmark.',
    weight_gain_steady: 'Weight gain becomes steady, usually a few hundred grams a week.',
    braxton_hicks: 'Braxton Hicks tightenings may begin — practice contractions, not labour.',
    colostrum_may_appear: 'A few drops of colostrum may leak from your breasts.',
    fundal_height_above_navel: 'The uterus is now a few centimetres above the navel.',
    pelvis_loosens: 'The pelvis loosens under the influence of relaxin.',
    sleep_harder: 'Comfortable sleeping positions get harder to find.',
    ribs_pressure: 'The growing uterus presses up against your ribs.',
    blood_pressure_watch: 'Blood pressure and urine are checked at each visit for signs of pre-eclampsia.',
    antenatal_visits_increase: 'Antenatal visits usually become more frequent from now.',
    heartburn_more: 'There is less room for your stomach, so heartburn gets more common.',
    fatigue_returns: 'Third-trimester tiredness returns, often quite suddenly.',
    less_room_lungs: 'Your lungs have less room, so deep breaths feel harder.',
    fundal_height_high: 'The top of the uterus sits high, just under the ribs.',
    appetite_smaller: 'Smaller meals feel better — there is little room left for a full stomach.',
    swelling_common: 'Mild swelling in the hands, feet and ankles is common.',
    back_pressure: 'The weight in front puts steady pressure on your lower back.',
    less_room_movement: 'Movements feel more like rolls and pushes than kicks.',
    lightening_drop: 'The baby may drop lower into the pelvis — often called lightening.',
    cervix_softens: 'The cervix softens and begins to thin in preparation for labour.',
    mucus_plug: 'The mucus plug may come away days or hours before labour.',
    contractions_may_start: 'Contractions can start at any time now.',
    cervix_dilates: 'The cervix starts to open once true labour begins.',
  },
  symptoms: {
    period_symptoms: 'Ordinary period symptoms — cramps and a heavy, tired feeling',
    fatigue: 'Deep tiredness, even after a full night of sleep',
    mood_swings: 'Mood that swings quickly, driven by hormones',
    ovulation_signs: 'A twinge on one side, and clear, stretchy discharge',
    breast_tenderness: 'Tender, heavier breasts',
    increased_appetite: 'A noticeably bigger appetite',
    no_symptoms_yet: 'Usually nothing at all — it is far too early for signs',
    bloating: 'Bloating and a tight, full feeling in the belly',
    light_spotting: 'Light spotting, which can be implantation bleeding',
    nausea: 'Nausea that can arrive at any time of day',
    frequent_urination: 'Needing the toilet more often',
    heightened_smell: 'A sharper sense of smell that turns familiar things unpleasant',
    food_aversions: 'Strong food aversions and cravings',
    headaches: 'Headaches, often linked to hormones or low fluids',
    constipation: 'Constipation as digestion slows down',
    heartburn: 'Heartburn and acid reflux, especially after meals',
    nausea_easing: 'Nausea that finally starts to fade',
    dizziness: 'Dizziness when you stand up too quickly',
    nasal_congestion: 'A blocked nose that has nothing to do with a cold',
    round_ligament_pain: 'Sharp, brief pulls low in the belly when you move',
    forgetfulness: 'Forgetfulness and trouble concentrating',
    skin_changes: 'Skin changes: darker patches, a line down the belly, or breakouts',
    nosebleeds: 'Occasional nosebleeds and bleeding gums',
    leg_cramps: 'Leg cramps, usually at night',
    back_ache: 'A dull ache in the lower back',
    vivid_dreams: 'Unusually vivid dreams',
    swollen_ankles: 'Swollen feet and ankles by the end of the day',
    hip_pain: 'Aching hips, particularly when lying on one side',
    shortness_breath: 'Getting out of breath more easily',
    discharge_increase: 'More vaginal discharge, thin and milky white',
    stretch_marks_itch: 'Itchy, stretching skin over the bump',
    varicose_veins: 'Varicose veins in the legs',
    hemorrhoids: 'Haemorrhoids, made worse by constipation',
    insomnia: 'Broken sleep and difficulty getting comfortable',
    braxton_hicks_symptom: 'Painless tightenings that come and go',
    restless_legs: 'Restless legs in the evening',
    pelvic_pressure: 'Heavy pressure low in the pelvis',
    carpal_tunnel: 'Tingling or numb fingers, especially in the morning',
    easier_breathing: 'Easier breathing once the baby drops',
    nesting_energy: 'A sudden urge to clean, sort and prepare',
    loose_stools: 'Looser stools, which can come before labour',
    contractions: 'Contractions that get longer, stronger and closer together',
  },
  tips: {
    start_folic_acid: 'Take 400 µg of folic acid daily — it protects the neural tube before you know you are pregnant.',
    track_cycle: 'Track your cycle so you know your fertile days and your dating is accurate later.',
    avoid_alcohol_smoking: 'Stop alcohol and smoking, and check any medication with your doctor.',
    gentle_movement: 'Keep moving gently — a daily walk helps circulation, mood and sleep.',
    prenatal_vitamin: 'Take a prenatal vitamin with folic acid and vitamin D.',
    hydrate: 'Drink water through the day; dehydration worsens tiredness and headaches.',
    take_test: 'A home test is most reliable from the day your period is due.',
    book_first_appointment: 'Book your first antenatal appointment — most take place between weeks 8 and 12.',
    small_frequent_meals: 'Eat small, frequent meals; an empty stomach makes nausea worse.',
    rest_when_tired: 'Rest without guilt. First-trimester tiredness is real and temporary.',
    first_scan_booking: 'Arrange your dating scan, usually offered between weeks 10 and 14.',
    talk_about_worries: 'Talk to someone you trust about how you are feeling — worry is normal.',
    fiber_rich_foods: 'Add fibre — vegetables, oats, pulses — to keep digestion moving.',
    first_trimester_screening: 'Discuss first-trimester screening options with your doctor or midwife.',
    iron_rich_foods: 'Include iron-rich foods with vitamin C to help absorption.',
    tell_employer: 'If you have not already, plan when to tell your employer and check your rights.',
    sleep_on_side: 'Start getting used to sleeping on your side, ideally the left.',
    maternity_clothes: 'Switch to softer waistbands before your clothes become uncomfortable.',
    moisturise_skin: 'Moisturise the bump daily — it will not prevent stretch marks, but it eases itching.',
    pelvic_floor_exercises: 'Do pelvic floor exercises daily; they help now and after birth.',
    talk_and_sing: 'Talk, read or sing to your bump — your baby is starting to hear.',
    anomaly_scan_booking: 'Book the anomaly scan, usually offered between weeks 18 and 22.',
    supportive_shoes: 'Wear supportive shoes; loosened ligaments make ankles less stable.',
    anomaly_scan: 'The anomaly scan checks your baby’s organs, growth and the placenta in detail.',
    rest_and_elevate_feet: 'Put your feet up when you can to ease swelling.',
    sun_protection: 'Use sun protection — pregnancy skin darkens more easily.',
    start_kick_awareness: 'Start noticing your baby’s pattern of movement.',
    birth_plan: 'Begin thinking about your birth preferences and where you want to give birth.',
    glucose_test_soon: 'Your gestational diabetes test will be offered soon, usually weeks 24–28.',
    antenatal_classes: 'Book antenatal classes — good ones fill up early.',
    glucose_test: 'Attend the glucose tolerance test if it is offered to you.',
    count_movements_daily: 'Get to know your baby’s daily pattern and call your midwife if it changes.',
    monitor_blood_pressure: 'Report headaches, vision changes or sudden swelling straight away.',
    hospital_bag_list: 'Start a list for your hospital bag — no need to pack it yet.',
    blood_tests_check: 'Blood tests around this point check for anaemia; anti-D is offered if your blood is Rh negative.',
    calcium_rich_foods: 'Include calcium-rich foods — your baby’s bones are hardening fast.',
    rest_and_nap: 'Take short naps if nights are broken; tiredness builds up quickly now.',
    breastfeeding_prep: 'Read about feeding options so the first days feel less unfamiliar.',
    hospital_bag: 'Pack your hospital bag so it is ready from week 36.',
    know_labour_signs: 'Know the signs of labour and when to call: regular contractions, waters breaking, bleeding.',
    monitor_swelling: 'Sudden swelling in the face or hands needs to be checked the same day.',
    install_car_seat: 'Fit and test the car seat while there is no hurry.',
    group_b_strep_test: 'Ask about group B strep testing where it is offered.',
    weekly_checkups: 'Appointments usually move to weekly from now on.',
    perineal_massage: 'Perineal massage from week 34 may reduce tearing during birth.',
    plan_route_hospital: 'Plan your route to hospital, and a backup if your driver is unavailable.',
    postpartum_support: 'Line up help for the first two weeks at home — meals, laundry, company.',
    monitor_movements_closely: 'Reduced movement always needs checking, even after your due date.',
  },
  milestones: {
    implantation_milestone: 'A pregnancy test can turn positive this week.',
    fetus_milestone: 'Your baby is officially a fetus now.',
    first_trimester_end: 'End of the first trimester — the risk of miscarriage drops significantly.',
    second_trimester_start: 'Welcome to the second trimester.',
    halfway: 'You are halfway there.',
    viability: 'From this week, babies born early have a real chance of surviving with specialist care.',
    third_trimester_start: 'The third trimester begins.',
    early_term: 'Your pregnancy is now considered early term.',
    full_term: 'Your baby is full term.',
    due_date: 'This is your due date week — only about 1 in 20 babies arrive exactly on the date.',
  },
  faq: [
    {
      question: 'How many months is {n} weeks pregnant?',
      answer: '{n} weeks is {months}. Pregnancy months do not divide evenly into weeks, so counting in weeks is more precise.',
    },
    {
      question: 'How big is my baby at {n} weeks?',
      answer: 'At {n} weeks your baby is around {size} — roughly {length} long and about {weight}. Healthy babies vary a lot around these averages.',
    },
    {
      question: 'What symptoms are normal at {n} weeks pregnant?',
      answer: 'The most common ones this week are listed above. Contact your doctor or midwife about heavy bleeding, severe pain, a fever, or any change in your baby’s movements.',
    },
  ],
  monthsLabel: 'about {months} months',
};
