import type { WeekPhrasebook } from './types';

export const esWeeks: WeekPhrasebook = {
  slugTemplate: 'semana-{n}',
  seoTitle: 'Semana {n} de embarazo: desarrollo, síntomas y consejos',
  seoDescription:
    'En la semana {n} de embarazo tu bebé mide más o menos como {size}. Descubre qué se desarrolla esta semana, cómo cambia tu cuerpo y los síntomas más frecuentes.',
  intro:
    'En la semana {n} de embarazo tu bebé tiene el tamaño aproximado de {size}. Estás en el {trimester}, y esta semana trae sus propios cambios — para tu bebé y para ti.',
  trimesterInline: ['primer trimestre', 'segundo trimestre', 'tercer trimestre'],
  introEarly:
    'La semana {n} se cuenta desde el primer día de tu última regla, así que ocurre antes de la concepción. Aun así importa: tu cuerpo está preparando las condiciones que necesita un embarazo.',
  expect: [
    'El principio del embarazo es invisible por fuera y muy ruidoso por dentro. Los síntomas van y vienen de un día a otro, y eso es normal. Quedan {left} semanas: esta semana lo que cuenta es el descanso, la comida suave y tu primera consulta.',
    'Los meses centrales suelen ser la parte más estable del embarazo. La energía vuelve, la barriga se nota y las revisiones se convierten en rutina. Quedan {left} semanas: buen momento para organizarte mientras te encuentras bien.',
    'La recta final exige mucho a tu cuerpo. Dormir cuesta más, los movimientos se vuelven lentos y las citas se acercan. Quedan {left} semanas: descansa, aprende a reconocer las señales de parto y ten la bolsa lista.',
  ],
  sizes: {
    not_yet: 'nada todavía — la concepción aún no ha ocurrido',
    poppy_seed: 'una semilla de amapola',
    sesame_seed: 'una semilla de sésamo',
    lentil: 'una lenteja',
    blueberry: 'un arándano',
    raspberry: 'una frambuesa',
    grape: 'una uva',
    kumquat: 'un kumquat',
    fig: 'un higo',
    lime: 'una lima',
    lemon: 'un limón',
    peach: 'un melocotón',
    apple: 'una manzana',
    avocado: 'un aguacate',
    pear: 'una pera',
    bell_pepper: 'un pimiento',
    mango: 'un mango',
    banana: 'un plátano',
    carrot: 'una zanahoria',
    papaya: 'una papaya',
    grapefruit: 'un pomelo',
    corn: 'una mazorca de maíz',
    cauliflower: 'una coliflor',
    lettuce: 'una lechuga',
    cabbage: 'un repollo',
    eggplant: 'una berenjena',
    squash: 'una calabaza cacahuete',
    cucumber: 'un pepino',
    coconut: 'un coco',
    napa_cabbage: 'una col china',
    pineapple: 'una piña',
    cantaloupe: 'un melón cantalupo',
    honeydew: 'un melón verde',
    romaine: 'una lechuga romana',
    chard: 'un manojo de acelgas',
    leek: 'un puerro',
    mini_watermelon: 'una sandía pequeña',
    pumpkin: 'una calabaza pequeña',
  },
  development: {
    prep_cycle: 'Todavía no hay bebé: tu cuerpo elimina el endometrio antiguo y empieza un ciclo nuevo.',
    egg_released: 'Un óvulo termina de madurar dentro del folículo, listo para salir.',
    ovulation: 'La ovulación ocurre hacia la mitad del ciclo; el óvulo puede fecundarse durante unas 24 horas.',
    fertilization: 'Si un espermatozoide llega al óvulo, la fecundación sucede en la trompa.',
    cell_division: 'La única célula se divide una y otra vez mientras viaja hacia el útero.',
    implantation: 'El grupo de células se instala en el endometrio: es la implantación.',
    placenta_begins: 'Las células que formarán la placenta comienzan a desarrollarse y producen hCG.',
    three_layers_form: 'Aparecen tres capas de células; cada una dará lugar a partes distintas del bebé.',
    neural_tube_forms: 'El tubo neural se cierra y se convertirá en el cerebro y la médula espinal.',
    heart_begins_beating: 'El diminuto tubo cardíaco empieza a latir, al principio como un simple aleteo.',
    circulation_starts: 'Se forman los primeros vasos sanguíneos y arranca la circulación.',
    arm_leg_buds: 'Aparecen pequeños brotes donde crecerán los brazos y las piernas.',
    facial_features_form: 'Dos puntos oscuros marcan el lugar de los ojos y la mandíbula toma forma.',
    brain_grows_fast: 'El cerebro crece muy deprisa: unas 100 células nuevas por minuto.',
    kidneys_form: 'Los riñones, el hígado y los pulmones empiezan a formarse.',
    fingers_toes_webbed: 'Se forman los dedos de manos y pies, todavía unidos por finas membranas.',
    tail_disappears: 'La pequeña cola embrionaria desaparece esta semana.',
    spontaneous_movements: 'Tu bebé ya se mueve solo, con demasiada suavidad para que lo notes.',
    all_organs_present: 'Todos los órganos principales están presentes, aunque ninguno está terminado.',
    heartbeat_audible_scan: 'El latido suele verse y escucharse en una ecografía temprana.',
    muscles_develop: 'Los músculos se desarrollan y las diminutas articulaciones empiezan a doblarse.',
    embryo_becomes_fetus: 'Tu bebé ya se llama feto: la etapa crítica de formación de órganos ha terminado.',
    fingernails_start: 'Aparecen los lechos de las uñas en dedos de manos y pies.',
    bones_hardening: 'El cartílago blando se va convirtiendo en hueso.',
    fingers_toes_separate: 'Los dedos ya están separados y las uñas empiezan a crecer.',
    tooth_buds_form: 'En las encías se forman los gérmenes dentales, para dentro de años.',
    reflexes_begin: 'Llegan los primeros reflejos: tu bebé cierra los dedos y abre la boca.',
    kidneys_make_urine: 'Los riñones empiezan a producir orina, que pasa a formar parte del líquido amniótico.',
    vocal_cords_form: 'Se forman las cuerdas vocales, aunque el sonido necesita aire para viajar.',
    fingerprints_form: 'En las yemas se forman huellas dactilares únicas.',
    external_genitals_form: 'Los genitales externos se están formando y podrán verse en una ecografía posterior.',
    facial_expressions: 'Los músculos de la cara empiezan a funcionar: tu bebé puede fruncir el ceño.',
    lanugo_appears: 'Un vello fino llamado lanugo empieza a cubrir la piel.',
    sucking_reflex: 'Aparece el reflejo de succión; tu bebé puede encontrar su pulgar.',
    hearing_begins: 'Los huesos del oído interno se endurecen y llegan los primeros sonidos.',
    taste_buds_form: 'Se forman las papilas gustativas y captan los sabores del líquido amniótico.',
    coordinated_movements: 'Los movimientos son más suaves y coordinados.',
    hears_your_voice: 'Tu bebé oye tu voz, tu latido y tu digestión.',
    eyes_move_slowly: 'Los ojos se mueven despacio bajo los párpados cerrados.',
    fat_under_skin: 'Se acumula grasa parda bajo la piel para ayudar a mantener el calor tras el nacimiento.',
    umbilical_cord_thickens: 'El cordón umbilical se vuelve más grueso y resistente.',
    sweat_glands_form: 'Bajo la piel en formación se desarrollan las glándulas sudoríparas.',
    hearing_sharpens: 'El oído se afina; los ruidos fuertes pueden sobresaltar a tu bebé.',
    myelin_forms: 'Una capa protectora llamada mielina empieza a recubrir los nervios.',
    yawning_hiccups: 'Tu bebé bosteza, tiene hipo y se estira dentro del líquido amniótico.',
    vernix_forms: 'Una capa cerosa, el vérnix, protege la piel del líquido.',
    brain_maps_senses: 'El cerebro está creando las zonas del olfato, el gusto, el oído, la vista y el tacto.',
    hair_on_head: 'Empieza a crecer pelo en la cabeza.',
    swallowing_practice: 'Tu bebé traga líquido amniótico y practica para alimentarse.',
    rapid_weight_gain: 'A partir de ahora el aumento de peso se acelera de forma notable.',
    taste_through_fluid: 'Lo que comes da sabor al líquido amniótico y tu bebé lo prueba.',
    marrow_makes_blood: 'La médula ósea asume la producción de glóbulos rojos.',
    grip_develops: 'Tu bebé agarra el cordón umbilical y toca lo que le rodea.',
    eyebrows_visible: 'Las cejas y las pestañas ya se ven.',
    lungs_prepare: 'En los pulmones se forman las ramificaciones que algún día llevarán aire.',
    responds_to_sound: 'Las voces conocidas y la música pueden hacer que se mueva o se calme.',
    skin_less_transparent: 'La piel se vuelve menos transparente a medida que se pigmenta.',
    lungs_make_surfactant: 'Los pulmones empiezan a producir surfactante, que los mantendrá abiertos al nacer.',
    inner_ear_complete: 'El oído interno está completo y también ayuda al equilibrio.',
    hair_gets_colour: 'El pelo empieza a coger color.',
    responds_to_light: 'Una luz fuerte sobre la barriga puede hacer que se gire.',
    eyes_open: 'Los párpados se abren por primera vez.',
    brain_waves_respond: 'Las ondas cerebrales ya responden al sonido y al tacto.',
    practices_breathing: 'Tu bebé practica movimientos respiratorios con líquido amniótico.',
    sleep_wake_cycles: 'Aparecen ciclos claros de sueño y vigilia, a menudo distintos de los tuyos.',
    recognises_voices: 'Tu bebé reconoce tu voz y puede calmarse cuando hablas.',
    dreams_rem: 'Comienza el sueño REM, la fase asociada a los sueños.',
    blinking: 'Tu bebé puede parpadear y las pestañas están completas.',
    bones_need_calcium: 'Los huesos se endurecen rápido y toman calcio de tu alimentación.',
    muscles_lungs_mature: 'Los músculos y los pulmones siguen madurando de forma constante.',
    lanugo_disappears: 'El fino lanugo empieza a desaparecer.',
    all_senses_working: 'Los cinco sentidos ya funcionan.',
    kicks_stronger: 'Las patadas se sienten más fuertes porque hay menos espacio.',
    head_down_position: 'Muchos bebés se colocan cabeza abajo por estas fechas: todavía hay sitio para girar.',
    fingernails_reach_tips: 'Las uñas llegan a la punta de los dedos.',
    immune_transfer: 'Los anticuerpos pasan de ti a tu bebé y crean sus primeras defensas.',
    skull_stays_soft: 'Los huesos del cráneo siguen blandos y separados para pasar por el canal del parto.',
    lungs_nearly_ready: 'Los pulmones están casi listos para respirar aire.',
    vernix_thickens: 'La capa de vérnix se hace más gruesa para proteger la piel.',
    eyes_focus: 'Tu bebé enfoca de cerca y sigue la luz.',
    kidneys_fully_developed: 'Los riñones están completamente desarrollados y el hígado procesa algunos desechos.',
    skin_smooths: 'La grasa rellena la piel y las arrugas se alisan.',
    gripping_strength: 'El agarre es lo bastante fuerte para sujetar tu dedo al nacer.',
    meconium_builds: 'En el intestino se acumula el meconio, las primeras heces oscuras.',
    fat_layers_finish: 'Se completan las últimas capas de grasa, que ayudarán a regular la temperatura.',
    lungs_ready: 'Los pulmones están listos y el cerebro y el sistema nervioso siguen madurando.',
    ready_for_birth: 'Tu bebé está listo para nacer y sigue creciendo hasta el parto.',
  },
  body: {
    period_starts: 'Tu regla marca el día uno: desde aquí se cuentan las semanas de embarazo.',
    uterus_lining_sheds: 'El endometrio se desprende y empieza a formarse uno nuevo.',
    fertile_window: 'Estás en los días más fértiles del ciclo.',
    cervical_mucus_changes: 'El moco cervical se vuelve transparente y elástico en la ovulación.',
    hormones_rising: 'Las hormonas suben de forma constante para sostener el embarazo inicial.',
    uterus_lining_thickens: 'El endometrio se engrosa preparándose para la implantación.',
    hcg_detectable: 'La hCG ya es detectable: es lo que mide un test de embarazo.',
    missed_period_soon: 'Tu regla tocaría ahora; la falta suele ser la primera señal.',
    blood_volume_rises: 'Tu volumen de sangre sigue aumentando para alimentar la placenta.',
    uterus_grows_slightly: 'El útero crece, aunque por fuera todavía no se note nada.',
    breast_changes: 'Los pechos se notan más llenos y las areolas pueden oscurecerse.',
    mucus_plug_forms: 'En el cuello del útero se forma el tapón mucoso que lo sella.',
    uterus_size_orange: 'Tu útero tiene más o menos el tamaño de una naranja grande.',
    skin_changes_body: 'El aumento del riego puede dejarte la piel luminosa — o con más granitos.',
    waist_thickens: 'La cintura aprieta antes de que se vea barriga.',
    uterus_rises_pelvis: 'El útero sale de la pelvis y ya se palpa en la parte baja.',
    nausea_may_ease: 'En muchas mujeres las náuseas empiezan a aflojar por estas fechas.',
    energy_returns: 'La energía vuelve según se estabilizan las hormonas.',
    showing_starts: 'Se empieza a ver una pequeña barriga, sobre todo al final del día.',
    uterus_grows_steadily: 'A partir de aquí el útero crece alrededor de un centímetro por semana.',
    nasal_membranes_swell: 'El mayor flujo de sangre hincha las mucosas de la nariz.',
    fundal_height_navel: 'El fondo del útero está a mitad de camino del ombligo.',
    ligaments_soften: 'Los ligamentos se ablandan y se estiran para dejar sitio.',
    balance_shifts: 'Tu centro de gravedad cambia y los movimientos se sienten distintos.',
    first_movements: 'Los primeros movimientos suelen notarse entre las semanas 18 y 22.',
    appetite_grows: 'El apetito aumenta porque tu bebé gana peso más rápido.',
    skin_pigment_changes: 'Los cambios de pigmento son habituales: la línea alba y manchas en la cara.',
    uterus_at_navel: 'El fondo del útero llega al ombligo, la referencia clásica de la semana 20.',
    weight_gain_steady: 'El aumento de peso se vuelve constante, unos cientos de gramos por semana.',
    braxton_hicks: 'Pueden empezar las contracciones de Braxton Hicks: son de práctica, no de parto.',
    colostrum_may_appear: 'Del pecho pueden salir unas gotas de calostro.',
    fundal_height_above_navel: 'El útero está ya unos centímetros por encima del ombligo.',
    pelvis_loosens: 'La pelvis se afloja por efecto de la relaxina.',
    sleep_harder: 'Cuesta más encontrar una postura cómoda para dormir.',
    ribs_pressure: 'El útero, que sigue creciendo, presiona hacia las costillas.',
    blood_pressure_watch: 'En cada visita se miran la tensión y la orina para descartar preeclampsia.',
    antenatal_visits_increase: 'A partir de ahora las revisiones suelen ser más frecuentes.',
    heartburn_more: 'El estómago tiene menos espacio y el ardor aparece más a menudo.',
    fatigue_returns: 'El cansancio del tercer trimestre vuelve, a veces de golpe.',
    less_room_lungs: 'Los pulmones tienen menos espacio y respirar hondo cuesta más.',
    fundal_height_high: 'El fondo del útero está alto, justo bajo las costillas.',
    appetite_smaller: 'Sientan mejor las comidas pequeñas: ya no hay sitio para un estómago lleno.',
    swelling_common: 'Es normal una hinchazón leve en manos, pies y tobillos.',
    back_pressure: 'El peso de delante presiona de forma constante la zona lumbar.',
    less_room_movement: 'Los movimientos se parecen más a giros y empujones que a patadas.',
    lightening_drop: 'El bebé puede bajar a la pelvis: es el llamado aligeramiento.',
    cervix_softens: 'El cuello del útero se ablanda y empieza a acortarse.',
    mucus_plug: 'El tapón mucoso puede salir días u horas antes del parto.',
    contractions_may_start: 'Las contracciones pueden empezar en cualquier momento.',
    cervix_dilates: 'Cuando comienza el parto de verdad, el cuello del útero se dilata.',
  },
  symptoms: {
    period_symptoms: 'Molestias normales de la regla: calambres y sensación de pesadez',
    fatigue: 'Cansancio profundo, incluso tras dormir toda la noche',
    mood_swings: 'Cambios de humor rápidos, por efecto hormonal',
    ovulation_signs: 'Un pinchazo en un lado y flujo transparente y elástico',
    breast_tenderness: 'Pechos sensibles y más pesados',
    increased_appetite: 'Un apetito claramente mayor',
    no_symptoms_yet: 'Normalmente nada: es demasiado pronto para notar señales',
    bloating: 'Hinchazón y sensación de tripa tirante',
    light_spotting: 'Un manchado leve, que puede ser sangrado de implantación',
    nausea: 'Náuseas que pueden aparecer a cualquier hora',
    frequent_urination: 'Ganas de ir al baño más a menudo',
    heightened_smell: 'Un olfato más fino que vuelve desagradables olores conocidos',
    food_aversions: 'Rechazos y antojos de comida muy marcados',
    headaches: 'Dolores de cabeza, a menudo por hormonas o falta de líquidos',
    constipation: 'Estreñimiento porque la digestión se enlentece',
    heartburn: 'Ardor y reflujo, sobre todo después de comer',
    nausea_easing: 'Náuseas que por fin empiezan a remitir',
    dizziness: 'Mareo al levantarte demasiado rápido',
    nasal_congestion: 'Nariz taponada sin ningún resfriado',
    round_ligament_pain: 'Pinchazos breves en la parte baja del vientre al moverte',
    forgetfulness: 'Olvidos y dificultad para concentrarte',
    skin_changes: 'Cambios en la piel: manchas, línea en la tripa o brotes de acné',
    nosebleeds: 'Sangrados de nariz ocasionales y encías sensibles',
    leg_cramps: 'Calambres en las piernas, casi siempre de noche',
    back_ache: 'Un dolor sordo en la zona lumbar',
    vivid_dreams: 'Sueños especialmente vívidos',
    swollen_ankles: 'Pies y tobillos hinchados al final del día',
    hip_pain: 'Caderas doloridas, sobre todo tumbada de lado',
    shortness_breath: 'Te quedas sin aire con más facilidad',
    discharge_increase: 'Más flujo vaginal, líquido y blanquecino',
    stretch_marks_itch: 'Piel tirante y con picor sobre la barriga',
    varicose_veins: 'Varices en las piernas',
    hemorrhoids: 'Hemorroides, empeoradas por el estreñimiento',
    insomnia: 'Sueño interrumpido y dificultad para ponerte cómoda',
    braxton_hicks_symptom: 'Endurecimientos indoloros de la tripa que van y vienen',
    restless_legs: 'Piernas inquietas por la noche',
    pelvic_pressure: 'Mucha presión en la zona baja de la pelvis',
    carpal_tunnel: 'Hormigueo o dedos dormidos, sobre todo por la mañana',
    easier_breathing: 'Respiras mejor cuando el bebé baja',
    nesting_energy: 'Un impulso repentino de limpiar, ordenar y preparar',
    loose_stools: 'Heces más blandas, que pueden preceder al parto',
    contractions: 'Contracciones cada vez más largas, fuertes y seguidas',
  },
  tips: {
    start_folic_acid: 'Toma 400 µg de ácido fólico al día: protege el tubo neural incluso antes de saber que estás embarazada.',
    track_cycle: 'Lleva un registro del ciclo: sabrás tus días fértiles y la datación será más precisa.',
    avoid_alcohol_smoking: 'Deja el alcohol y el tabaco y consulta con tu médico cualquier medicación.',
    gentle_movement: 'Muévete con suavidad: un paseo diario mejora circulación, ánimo y sueño.',
    prenatal_vitamin: 'Toma un suplemento prenatal con ácido fólico y vitamina D.',
    hydrate: 'Bebe agua a lo largo del día; la deshidratación empeora el cansancio y el dolor de cabeza.',
    take_test: 'El test de casa es más fiable desde el día en que te tocaría la regla.',
    book_first_appointment: 'Pide tu primera consulta prenatal: suele ser entre las semanas 8 y 12.',
    small_frequent_meals: 'Come poco y a menudo: el estómago vacío empeora las náuseas.',
    rest_when_tired: 'Descansa sin culpa. El cansancio del primer trimestre es real y pasajero.',
    first_scan_booking: 'Organiza la ecografía de datación, habitual entre las semanas 10 y 14.',
    talk_about_worries: 'Habla con alguien de confianza sobre cómo te sientes: preocuparse es normal.',
    fiber_rich_foods: 'Suma fibra —verduras, avena, legumbres— para que la digestión no se pare.',
    first_trimester_screening: 'Comenta con tu médico o matrona el cribado del primer trimestre.',
    iron_rich_foods: 'Combina alimentos ricos en hierro con vitamina C para absorberlo mejor.',
    tell_employer: 'Decide cuándo se lo dirás a tu empresa y revisa tus derechos.',
    sleep_on_side: 'Ve acostumbrándote a dormir de lado, mejor sobre el izquierdo.',
    maternity_clothes: 'Cambia a cinturas blandas antes de que la ropa te moleste.',
    moisturise_skin: 'Hidrata la barriga a diario: no evita las estrías, pero calma el picor.',
    pelvic_floor_exercises: 'Haz ejercicios de suelo pélvico cada día; ayudan ahora y después del parto.',
    talk_and_sing: 'Habla, lee o canta a tu barriga: tu bebé empieza a oír.',
    anomaly_scan_booking: 'Pide la ecografía morfológica, habitual entre las semanas 18 y 22.',
    supportive_shoes: 'Usa calzado estable: los ligamentos laxos hacen los tobillos menos seguros.',
    anomaly_scan: 'La ecografía morfológica revisa en detalle los órganos, el crecimiento y la placenta.',
    rest_and_elevate_feet: 'Sube los pies siempre que puedas para bajar la hinchazón.',
    sun_protection: 'Usa protección solar: en el embarazo la piel se mancha con más facilidad.',
    start_kick_awareness: 'Empieza a fijarte en cómo y cuándo se mueve tu bebé.',
    birth_plan: 'Empieza a pensar en tus preferencias de parto y en dónde quieres dar a luz.',
    glucose_test_soon: 'La prueba de diabetes gestacional llegará pronto, entre las semanas 24 y 28.',
    antenatal_classes: 'Apúntate a clases de preparación al parto: las buenas se llenan pronto.',
    glucose_test: 'Hazte el test de sobrecarga de glucosa si te lo ofrecen.',
    count_movements_daily: 'Aprende el patrón diario de tu bebé y llama si cambia.',
    monitor_blood_pressure: 'Avisa de inmediato si tienes dolor de cabeza, visión borrosa o hinchazón repentina.',
    hospital_bag_list: 'Empieza la lista de la bolsa del hospital; hacerla puede esperar.',
    blood_tests_check: 'Por estas fechas se revisa la anemia; si eres Rh negativa te ofrecerán la gammaglobulina anti-D.',
    calcium_rich_foods: 'Incluye alimentos ricos en calcio: los huesos de tu bebé se endurecen deprisa.',
    rest_and_nap: 'Echa siestas cortas si las noches son malas; el cansancio se acumula.',
    breastfeeding_prep: 'Infórmate sobre la lactancia para que los primeros días te resulten menos ajenos.',
    hospital_bag: 'Prepara la bolsa del hospital para tenerla lista desde la semana 36.',
    know_labour_signs: 'Conoce las señales de parto: contracciones regulares, rotura de aguas, sangrado.',
    monitor_swelling: 'Una hinchazón repentina en cara o manos hay que valorarla el mismo día.',
    install_car_seat: 'Instala y prueba la silla del coche ahora, sin prisas.',
    group_b_strep_test: 'Pregunta por el cultivo de estreptococo del grupo B.',
    weekly_checkups: 'A partir de ahora las revisiones suelen pasar a ser semanales.',
    perineal_massage: 'El masaje perineal desde la semana 34 puede reducir los desgarros.',
    plan_route_hospital: 'Planifica la ruta al hospital y una alternativa si quien conduce no está.',
    postpartum_support: 'Organiza ayuda para las dos primeras semanas en casa: comidas, colada, compañía.',
    monitor_movements_closely: 'Si notas menos movimientos, hay que consultarlo siempre, incluso pasada la fecha.',
  },
  milestones: {
    implantation_milestone: 'Esta semana un test de embarazo ya puede dar positivo.',
    fetus_milestone: 'Tu bebé es oficialmente un feto.',
    first_trimester_end: 'Fin del primer trimestre: el riesgo de aborto baja de forma notable.',
    second_trimester_start: 'Bienvenida al segundo trimestre.',
    halfway: 'Estás a mitad de camino.',
    viability: 'Desde esta semana los bebés nacidos antes de tiempo tienen posibilidades reales de sobrevivir con cuidados intensivos.',
    third_trimester_start: 'Empieza el tercer trimestre.',
    early_term: 'Tu embarazo se considera ya a término precoz.',
    full_term: 'Tu bebé está a término.',
    due_date: 'Es la semana de tu fecha probable de parto: solo uno de cada veinte bebés nace ese día exacto.',
  },
  faq: [
    {
      question: '¿Cuántos meses son {n} semanas de embarazo?',
      answer: '{n} semanas equivalen a {months}. Los meses no se dividen en semanas exactas, por eso contar en semanas es más preciso.',
    },
    {
      question: '¿Qué tamaño tiene mi bebé en la semana {n}?',
      answer: 'En la semana {n} tu bebé tiene el tamaño aproximado de {size}: unos {length} y alrededor de {weight}. Los bebés sanos varían mucho respecto a estas medias.',
    },
    {
      question: '¿Qué síntomas son normales en la semana {n}?',
      answer: 'Los más frecuentes de esta semana están arriba. Consulta con tu médico o matrona si tienes sangrado abundante, dolor intenso, fiebre o notas cambios en los movimientos de tu bebé.',
    },
  ],
  monthsLabel: 'unos {months} meses',
};
