import type { WeekPhrasebook } from './types';

export const frWeeks: WeekPhrasebook = {
  slugTemplate: 'semaine-{n}',
  seoTitle: '{n} semaines de grossesse : développement, symptômes et conseils',
  seoDescription:
    'À {n} semaines de grossesse, votre bébé mesure à peu près la taille d’{size}. Découvrez ce qui se développe cette semaine, comment votre corps change et les symptômes fréquents.',
  intro:
    'À {n} semaines de grossesse, votre bébé a environ la taille d’{size}. Vous êtes dans le {trimester}, et cette semaine apporte ses propres changements — pour votre bébé comme pour vous.',
  trimesterInline: ['premier trimestre', 'deuxième trimestre', 'troisième trimestre'],
  introEarly:
    'La semaine {n} se compte à partir du premier jour de vos dernières règles : elle précède donc la conception. Elle compte quand même, car votre corps met en place les conditions nécessaires à une grossesse.',
  expect: [
    'Le début de grossesse est invisible de l’extérieur et très bruyant à l’intérieur. Les symptômes vont et viennent d’un jour à l’autre, et c’est normal. Il reste {left} semaines : cette semaine, l’essentiel est le repos, une alimentation douce et votre première consultation.',
    'Les mois du milieu sont souvent la période la plus stable de la grossesse. L’énergie revient, le ventre s’arrondit, les rendez-vous deviennent une routine. Il reste {left} semaines : le bon moment pour organiser la suite pendant que vous vous sentez bien.',
    'La dernière ligne droite demande beaucoup à votre corps. Le sommeil devient difficile, les mouvements ralentissent, les rendez-vous se rapprochent. Il reste {left} semaines : reposez-vous, apprenez à reconnaître les signes du travail et gardez votre valise prête.',
  ],
  sizes: {
    not_yet: 'rien encore — la conception n’a pas eu lieu',
    poppy_seed: 'une graine de pavot',
    sesame_seed: 'une graine de sésame',
    lentil: 'une lentille',
    blueberry: 'une myrtille',
    raspberry: 'une framboise',
    grape: 'un grain de raisin',
    kumquat: 'un kumquat',
    fig: 'une figue',
    lime: 'un citron vert',
    lemon: 'un citron',
    peach: 'une pêche',
    apple: 'une pomme',
    avocado: 'un avocat',
    pear: 'une poire',
    bell_pepper: 'un poivron',
    mango: 'une mangue',
    banana: 'une banane',
    carrot: 'une carotte',
    papaya: 'une papaye',
    grapefruit: 'un pamplemousse',
    corn: 'un épi de maïs',
    cauliflower: 'un chou-fleur',
    lettuce: 'une laitue',
    cabbage: 'un chou',
    eggplant: 'une aubergine',
    squash: 'une courge butternut',
    cucumber: 'un concombre',
    coconut: 'une noix de coco',
    napa_cabbage: 'un chou chinois',
    pineapple: 'un ananas',
    cantaloupe: 'un melon cantaloup',
    honeydew: 'un melon miel',
    romaine: 'une laitue romaine',
    chard: 'une botte de blettes',
    leek: 'un poireau',
    mini_watermelon: 'une petite pastèque',
    pumpkin: 'un petit potiron',
  },
  development: {
    prep_cycle: 'Il n’y a pas encore de bébé : votre corps élimine l’ancienne muqueuse et démarre un nouveau cycle.',
    egg_released: 'Un ovule achève sa maturation dans le follicule, prêt à être libéré.',
    ovulation: 'L’ovulation a lieu vers le milieu du cycle ; l’ovule est fécondable pendant environ 24 heures.',
    fertilization: 'Si un spermatozoïde rencontre l’ovule, la fécondation se produit dans la trompe.',
    cell_division: 'La cellule unique se divise sans cesse pendant son trajet vers l’utérus.',
    implantation: 'L’amas de cellules s’installe dans la muqueuse utérine : c’est la nidation.',
    placenta_begins: 'Les cellules qui formeront le placenta se mettent en place et produisent l’hCG.',
    three_layers_form: 'Trois couches de cellules apparaissent ; chacune donnera des parties différentes du bébé.',
    neural_tube_forms: 'Le tube neural se referme et deviendra le cerveau et la moelle épinière.',
    heart_begins_beating: 'Le minuscule tube cardiaque commence à battre, d’abord comme un simple frémissement.',
    circulation_starts: 'Les premiers vaisseaux se forment et la circulation démarre.',
    arm_leg_buds: 'De petits bourgeons apparaissent là où pousseront les bras et les jambes.',
    facial_features_form: 'Deux points sombres marquent l’emplacement des yeux et la mâchoire se dessine.',
    brain_grows_fast: 'Le cerveau grandit vite : environ 100 nouvelles cellules par minute.',
    kidneys_form: 'Les reins, le foie et les poumons commencent à se former.',
    fingers_toes_webbed: 'Les doigts et les orteils se forment, encore reliés par de fines membranes.',
    tail_disappears: 'La petite queue embryonnaire disparaît cette semaine.',
    spontaneous_movements: 'Votre bébé bouge déjà spontanément, bien trop doucement pour que vous le sentiez.',
    all_organs_present: 'Tous les grands organes sont en place, même si aucun n’est achevé.',
    heartbeat_audible_scan: 'Le cœur se voit et s’entend généralement à l’échographie précoce.',
    muscles_develop: 'Les muscles se développent et les minuscules articulations commencent à plier.',
    embryo_becomes_fetus: 'Votre bébé s’appelle désormais fœtus : la phase critique de formation des organes est terminée.',
    fingernails_start: 'Les lits des ongles apparaissent sur les doigts et les orteils.',
    bones_hardening: 'Le cartilage souple se transforme peu à peu en os.',
    fingers_toes_separate: 'Les doigts sont séparés et les ongles commencent à pousser.',
    tooth_buds_form: 'Les germes dentaires se forment dans les gencives, pour dans plusieurs années.',
    reflexes_begin: 'Les premiers réflexes arrivent : votre bébé referme les doigts et ouvre la bouche.',
    kidneys_make_urine: 'Les reins produisent de l’urine, qui rejoint le liquide amniotique.',
    vocal_cords_form: 'Les cordes vocales se forment, même si le son a besoin d’air pour se propager.',
    fingerprints_form: 'Des empreintes digitales uniques se dessinent au bout des doigts.',
    external_genitals_form: 'Les organes génitaux externes se forment et pourront être visibles plus tard.',
    facial_expressions: 'Les muscles du visage entrent en action : votre bébé peut froncer les sourcils.',
    lanugo_appears: 'Un fin duvet, le lanugo, commence à recouvrir la peau.',
    sucking_reflex: 'Le réflexe de succion apparaît ; votre bébé peut trouver son pouce.',
    hearing_begins: 'Les os de l’oreille interne durcissent et les premiers sons passent.',
    taste_buds_form: 'Les papilles gustatives se forment et perçoivent les saveurs du liquide amniotique.',
    coordinated_movements: 'Les mouvements deviennent plus fluides et mieux coordonnés.',
    hears_your_voice: 'Votre bébé entend votre voix, votre cœur et votre digestion.',
    eyes_move_slowly: 'Les yeux bougent lentement sous les paupières fermées.',
    fat_under_skin: 'De la graisse brune se forme sous la peau pour aider à garder la chaleur après la naissance.',
    umbilical_cord_thickens: 'Le cordon ombilical s’épaissit et se renforce.',
    sweat_glands_form: 'Les glandes sudoripares se développent sous la peau en formation.',
    hearing_sharpens: 'L’audition s’affine ; les bruits forts peuvent faire sursauter votre bébé.',
    myelin_forms: 'Une gaine protectrice, la myéline, commence à recouvrir les nerfs.',
    yawning_hiccups: 'Votre bébé bâille, a le hoquet et s’étire dans le liquide amniotique.',
    vernix_forms: 'Un enduit cireux, le vernix, protège la peau du liquide.',
    brain_maps_senses: 'Le cerveau met en place les zones de l’odorat, du goût, de l’ouïe, de la vue et du toucher.',
    hair_on_head: 'Les cheveux commencent à pousser sur le crâne.',
    swallowing_practice: 'Votre bébé avale du liquide amniotique et s’entraîne à téter.',
    rapid_weight_gain: 'À partir de maintenant, la prise de poids s’accélère nettement.',
    taste_through_fluid: 'Ce que vous mangez parfume le liquide amniotique, et votre bébé le goûte.',
    marrow_makes_blood: 'La moelle osseuse prend en charge la fabrication des globules rouges.',
    grip_develops: 'Votre bébé attrape le cordon et touche ce qui l’entoure.',
    eyebrows_visible: 'Les sourcils et les cils sont désormais visibles.',
    lungs_prepare: 'Les poumons forment les ramifications qui porteront un jour l’air.',
    responds_to_sound: 'Les voix familières et la musique peuvent le faire bouger ou l’apaiser.',
    skin_less_transparent: 'La peau devient moins transparente à mesure qu’elle se pigmente.',
    lungs_make_surfactant: 'Les poumons produisent du surfactant, qui les maintiendra ouverts après la naissance.',
    inner_ear_complete: 'L’oreille interne est complète et participe aussi à l’équilibre.',
    hair_gets_colour: 'Les cheveux commencent à se colorer.',
    responds_to_light: 'Une lumière vive sur le ventre peut le faire se détourner.',
    eyes_open: 'Les paupières s’ouvrent pour la première fois.',
    brain_waves_respond: 'Les ondes cérébrales répondent maintenant au son et au toucher.',
    practices_breathing: 'Votre bébé s’entraîne à respirer avec du liquide amniotique.',
    sleep_wake_cycles: 'Des cycles nets de sommeil et d’éveil apparaissent, souvent différents des vôtres.',
    recognises_voices: 'Votre bébé reconnaît votre voix et peut s’apaiser quand vous parlez.',
    dreams_rem: 'Le sommeil paradoxal commence — la phase associée aux rêves.',
    blinking: 'Votre bébé cligne des yeux et ses cils sont complets.',
    bones_need_calcium: 'Les os durcissent vite et puisent du calcium dans votre alimentation.',
    muscles_lungs_mature: 'Les muscles et les poumons continuent de mûrir régulièrement.',
    lanugo_disappears: 'Le fin duvet du lanugo commence à disparaître.',
    all_senses_working: 'Les cinq sens fonctionnent désormais.',
    kicks_stronger: 'Les coups sont plus francs, car la place se réduit.',
    head_down_position: 'Beaucoup de bébés se placent tête en bas à cette période : il reste de la place pour tourner.',
    fingernails_reach_tips: 'Les ongles atteignent le bout des doigts.',
    immune_transfer: 'Des anticorps passent de vous à votre bébé et construisent ses premières défenses.',
    skull_stays_soft: 'Les os du crâne restent souples et séparés pour passer dans le bassin.',
    lungs_nearly_ready: 'Les poumons sont presque prêts à respirer l’air.',
    vernix_thickens: 'La couche de vernix s’épaissit pour protéger la peau.',
    eyes_focus: 'Votre bébé fait le point de près et suit la lumière.',
    kidneys_fully_developed: 'Les reins sont complètement développés et le foie traite certains déchets.',
    skin_smooths: 'La graisse remplit la peau et les plis s’effacent.',
    gripping_strength: 'Sa poigne est assez forte pour serrer votre doigt à la naissance.',
    meconium_builds: 'Le méconium, les premières selles foncées, s’accumule dans l’intestin.',
    fat_layers_finish: 'Les dernières couches de graisse se mettent en place et aideront à réguler la température.',
    lungs_ready: 'Les poumons sont prêts ; le cerveau et le système nerveux continuent de mûrir.',
    ready_for_birth: 'Votre bébé est prêt à naître et grandit encore jusqu’au travail.',
  },
  body: {
    period_starts: 'Vos règles marquent le jour un : c’est de là que se comptent les semaines de grossesse.',
    uterus_lining_sheds: 'La muqueuse utérine s’élimine et une nouvelle commence à se construire.',
    fertile_window: 'Vous êtes dans les jours les plus fertiles du cycle.',
    cervical_mucus_changes: 'La glaire cervicale devient claire et filante autour de l’ovulation.',
    hormones_rising: 'Les hormones montent régulièrement pour soutenir le début de grossesse.',
    uterus_lining_thickens: 'La muqueuse utérine s’épaissit en vue de la nidation.',
    hcg_detectable: 'L’hCG devient détectable : c’est ce que mesure un test de grossesse.',
    missed_period_soon: 'Vos règles seraient attendues maintenant ; leur absence est souvent le premier signe.',
    blood_volume_rises: 'Votre volume sanguin continue d’augmenter pour alimenter le placenta.',
    uterus_grows_slightly: 'L’utérus grandit, même si rien ne se voit encore de l’extérieur.',
    breast_changes: 'Les seins sont plus lourds et les aréoles peuvent foncer.',
    mucus_plug_forms: 'Le bouchon muqueux se forme dans le col et scelle l’utérus.',
    uterus_size_orange: 'Votre utérus a à peu près la taille d’une grosse orange.',
    skin_changes_body: 'La circulation accrue peut rendre la peau éclatante — ou plus sujette aux imperfections.',
    waist_thickens: 'La taille serre déjà avant que le ventre ne se voie.',
    uterus_rises_pelvis: 'L’utérus sort du bassin et se palpe en bas du ventre.',
    nausea_may_ease: 'Chez beaucoup de femmes, les nausées commencent à s’atténuer.',
    energy_returns: 'L’énergie revient à mesure que les hormones se stabilisent.',
    showing_starts: 'Un petit ventre devient visible, surtout en fin de journée.',
    uterus_grows_steadily: 'L’utérus grandit désormais d’environ un centimètre par semaine.',
    nasal_membranes_swell: 'L’afflux de sang gonfle les muqueuses du nez.',
    fundal_height_navel: 'Le haut de l’utérus se situe à mi-chemin du nombril.',
    ligaments_soften: 'Les ligaments s’assouplissent et s’étirent pour faire de la place.',
    balance_shifts: 'Votre centre de gravité se déplace et les mouvements changent.',
    first_movements: 'Les premiers mouvements se sentent souvent entre 18 et 22 semaines.',
    appetite_grows: 'L’appétit augmente car votre bébé prend du poids plus vite.',
    skin_pigment_changes: 'Les changements de pigmentation sont fréquents : ligne brune sur le ventre, taches sur le visage.',
    uterus_at_navel: 'Le haut de l’utérus atteint le nombril, le repère classique de la 20e semaine.',
    weight_gain_steady: 'La prise de poids devient régulière, souvent quelques centaines de grammes par semaine.',
    braxton_hicks: 'Les contractions de Braxton Hicks peuvent commencer : ce sont des essais, pas le travail.',
    colostrum_may_appear: 'Quelques gouttes de colostrum peuvent perler.',
    fundal_height_above_navel: 'L’utérus dépasse maintenant le nombril de quelques centimètres.',
    pelvis_loosens: 'Le bassin se relâche sous l’effet de la relaxine.',
    sleep_harder: 'Trouver une position confortable pour dormir devient difficile.',
    ribs_pressure: 'L’utérus qui grandit appuie contre les côtes.',
    blood_pressure_watch: 'À chaque visite, tension et urines sont contrôlées pour dépister la prééclampsie.',
    antenatal_visits_increase: 'Les consultations deviennent généralement plus fréquentes.',
    heartburn_more: 'L’estomac a moins de place et les brûlures sont plus fréquentes.',
    fatigue_returns: 'La fatigue du troisième trimestre revient, souvent d’un coup.',
    less_room_lungs: 'Les poumons ont moins de place et les respirations profondes coûtent plus.',
    fundal_height_high: 'Le haut de l’utérus est haut, juste sous les côtes.',
    appetite_smaller: 'Les petits repas passent mieux : il reste peu de place pour un estomac plein.',
    swelling_common: 'Un léger gonflement des mains, des pieds et des chevilles est courant.',
    back_pressure: 'Le poids à l’avant met le bas du dos sous pression constante.',
    less_room_movement: 'Les mouvements ressemblent plus à des roulades qu’à des coups.',
    lightening_drop: 'Le bébé peut descendre dans le bassin : c’est la descente.',
    cervix_softens: 'Le col se ramollit et commence à se raccourcir.',
    mucus_plug: 'Le bouchon muqueux peut se détacher quelques jours ou heures avant le travail.',
    contractions_may_start: 'Les contractions peuvent démarrer à tout moment.',
    cervix_dilates: 'Une fois le vrai travail commencé, le col se dilate.',
  },
  symptoms: {
    period_symptoms: 'Des symptômes de règles habituels : crampes et sensation de lourdeur',
    fatigue: 'Une fatigue profonde, même après une nuit complète',
    mood_swings: 'Une humeur qui change vite, sous l’effet des hormones',
    ovulation_signs: 'Un tiraillement d’un côté et des pertes claires et filantes',
    breast_tenderness: 'Des seins sensibles et plus lourds',
    increased_appetite: 'Un appétit nettement plus grand',
    no_symptoms_yet: 'En général rien du tout : il est bien trop tôt',
    bloating: 'Des ballonnements et un ventre tendu',
    light_spotting: 'De légers saignements, parfois liés à la nidation',
    nausea: 'Des nausées qui peuvent survenir à toute heure',
    frequent_urination: 'Des envies d’uriner plus fréquentes',
    heightened_smell: 'Un odorat plus fin qui rend désagréables des odeurs familières',
    food_aversions: 'Des dégoûts et des envies alimentaires marqués',
    headaches: 'Des maux de tête, souvent hormonaux ou liés au manque d’eau',
    constipation: 'De la constipation, car la digestion ralentit',
    heartburn: 'Des brûlures d’estomac et des remontées acides, surtout après les repas',
    nausea_easing: 'Des nausées qui commencent enfin à s’estomper',
    dizziness: 'Des vertiges quand vous vous levez trop vite',
    nasal_congestion: 'Un nez bouché sans le moindre rhume',
    round_ligament_pain: 'De brèves douleurs en bas du ventre quand vous bougez',
    forgetfulness: 'Des oublis et des difficultés de concentration',
    skin_changes: 'Des changements de peau : taches, ligne brune ou boutons',
    nosebleeds: 'Des saignements de nez occasionnels et des gencives sensibles',
    leg_cramps: 'Des crampes dans les jambes, surtout la nuit',
    back_ache: 'Une douleur sourde en bas du dos',
    vivid_dreams: 'Des rêves particulièrement vifs',
    swollen_ankles: 'Des pieds et des chevilles gonflés en fin de journée',
    hip_pain: 'Des hanches douloureuses, surtout allongée sur le côté',
    shortness_breath: 'Un souffle plus court qu’avant',
    discharge_increase: 'Des pertes vaginales plus abondantes, fluides et blanchâtres',
    stretch_marks_itch: 'Une peau tendue qui démange sur le ventre',
    varicose_veins: 'Des varices aux jambes',
    hemorrhoids: 'Des hémorroïdes, aggravées par la constipation',
    insomnia: 'Un sommeil haché et des difficultés à trouver une position',
    braxton_hicks_symptom: 'Des durcissements indolores du ventre qui vont et viennent',
    restless_legs: 'Des jambes sans repos le soir',
    pelvic_pressure: 'Une forte pression en bas du bassin',
    carpal_tunnel: 'Des doigts qui fourmillent ou s’engourdissent, surtout le matin',
    easier_breathing: 'Une respiration plus facile une fois le bébé descendu',
    nesting_energy: 'Une envie soudaine de ranger, nettoyer et tout préparer',
    loose_stools: 'Des selles plus molles, qui peuvent précéder le travail',
    contractions: 'Des contractions de plus en plus longues, fortes et rapprochées',
  },
  tips: {
    start_folic_acid: 'Prenez 400 µg d’acide folique par jour : il protège le tube neural avant même que vous sachiez que vous êtes enceinte.',
    track_cycle: 'Suivez votre cycle : vous connaîtrez vos jours fertiles et la datation sera plus juste.',
    avoid_alcohol_smoking: 'Arrêtez l’alcool et le tabac, et faites vérifier vos médicaments par un médecin.',
    gentle_movement: 'Bougez en douceur : une marche quotidienne aide la circulation, le moral et le sommeil.',
    prenatal_vitamin: 'Prenez une vitamine prénatale avec acide folique et vitamine D.',
    hydrate: 'Buvez de l’eau tout au long de la journée ; la déshydratation aggrave fatigue et maux de tête.',
    take_test: 'Un test à domicile est fiable dès le jour où vos règles sont attendues.',
    book_first_appointment: 'Prenez votre première consultation prénatale, généralement entre 8 et 12 semaines.',
    small_frequent_meals: 'Mangez peu et souvent : l’estomac vide aggrave les nausées.',
    rest_when_tired: 'Reposez-vous sans culpabiliser. La fatigue du premier trimestre est réelle et passagère.',
    first_scan_booking: 'Organisez l’échographie de datation, proposée entre 10 et 14 semaines.',
    talk_about_worries: 'Parlez de ce que vous ressentez à quelqu’un de confiance : s’inquiéter est normal.',
    fiber_rich_foods: 'Ajoutez des fibres — légumes, avoine, légumineuses — pour garder un bon transit.',
    first_trimester_screening: 'Discutez du dépistage du premier trimestre avec votre médecin ou sage-femme.',
    iron_rich_foods: 'Associez les aliments riches en fer à de la vitamine C pour mieux l’absorber.',
    tell_employer: 'Choisissez le moment d’en parler à votre employeur et vérifiez vos droits.',
    sleep_on_side: 'Habituez-vous à dormir sur le côté, de préférence à gauche.',
    maternity_clothes: 'Passez aux tailles souples avant que vos vêtements ne vous gênent.',
    moisturise_skin: 'Hydratez le ventre chaque jour : cela n’évite pas les vergetures, mais calme les démangeaisons.',
    pelvic_floor_exercises: 'Faites des exercices de périnée tous les jours ; ils aident maintenant et après l’accouchement.',
    talk_and_sing: 'Parlez, lisez ou chantez à votre ventre : votre bébé commence à entendre.',
    anomaly_scan_booking: 'Programmez l’échographie morphologique, proposée entre 18 et 22 semaines.',
    supportive_shoes: 'Portez des chaussures stables : les ligaments détendus fragilisent les chevilles.',
    anomaly_scan: 'L’échographie morphologique examine en détail les organes, la croissance et le placenta.',
    rest_and_elevate_feet: 'Surélevez vos jambes dès que possible pour limiter les œdèmes.',
    sun_protection: 'Protégez-vous du soleil : la peau se pigmente plus facilement pendant la grossesse.',
    start_kick_awareness: 'Commencez à repérer quand et comment votre bébé bouge.',
    birth_plan: 'Commencez à réfléchir à vos souhaits pour l’accouchement et au lieu de naissance.',
    glucose_test_soon: 'Le test de diabète gestationnel arrive bientôt, entre 24 et 28 semaines.',
    antenatal_classes: 'Inscrivez-vous à la préparation à la naissance : les bonnes places partent vite.',
    glucose_test: 'Faites le test d’hyperglycémie provoquée s’il vous est proposé.',
    count_movements_daily: 'Apprenez le rythme quotidien de votre bébé et appelez s’il change.',
    monitor_blood_pressure: 'Signalez immédiatement maux de tête, troubles visuels ou gonflement soudain.',
    hospital_bag_list: 'Commencez la liste de la valise de maternité ; la préparer peut attendre.',
    blood_tests_check: 'À cette période, on vérifie l’anémie ; si vous êtes rhésus négatif, l’anti-D vous sera proposé.',
    calcium_rich_foods: 'Mangez des aliments riches en calcium : les os de votre bébé durcissent vite.',
    rest_and_nap: 'Faites de courtes siestes si les nuits sont hachées ; la fatigue s’accumule.',
    breastfeeding_prep: 'Renseignez-vous sur l’allaitement pour que les premiers jours soient moins déroutants.',
    hospital_bag: 'Préparez la valise de maternité pour qu’elle soit prête dès 36 semaines.',
    know_labour_signs: 'Connaissez les signes du travail : contractions régulières, perte des eaux, saignement.',
    monitor_swelling: 'Un gonflement soudain du visage ou des mains doit être vu le jour même.',
    install_car_seat: 'Installez et testez le siège auto pendant qu’il n’y a pas d’urgence.',
    group_b_strep_test: 'Demandez le dépistage du streptocoque B là où il est proposé.',
    weekly_checkups: 'Les rendez-vous deviennent généralement hebdomadaires.',
    perineal_massage: 'Le massage du périnée dès 34 semaines peut réduire les déchirures.',
    plan_route_hospital: 'Préparez le trajet vers la maternité et une solution de secours.',
    postpartum_support: 'Organisez de l’aide pour les deux premières semaines : repas, linge, présence.',
    monitor_movements_closely: 'Des mouvements diminués doivent toujours être vérifiés, même après le terme.',
  },
  milestones: {
    implantation_milestone: 'Un test de grossesse peut devenir positif cette semaine.',
    fetus_milestone: 'Votre bébé est officiellement un fœtus.',
    first_trimester_end: 'Fin du premier trimestre : le risque de fausse couche baisse nettement.',
    second_trimester_start: 'Bienvenue dans le deuxième trimestre.',
    halfway: 'Vous êtes à mi-parcours.',
    viability: 'À partir de cette semaine, les bébés nés très tôt ont de réelles chances de survie avec des soins intensifs.',
    third_trimester_start: 'Le troisième trimestre commence.',
    early_term: 'Votre grossesse est désormais considérée comme à terme précoce.',
    full_term: 'Votre bébé est à terme.',
    due_date: 'C’est la semaine du terme : à peine un bébé sur vingt naît exactement à la date prévue.',
  },
  faq: [
    {
      question: 'Combien de mois font {n} semaines de grossesse ?',
      answer: '{n} semaines correspondent à {months}. Les mois ne se divisent pas en semaines entières, c’est pourquoi compter en semaines est plus précis.',
    },
    {
      question: 'Quelle est la taille de mon bébé à {n} semaines ?',
      answer: 'À {n} semaines, votre bébé a environ la taille d’{size} : à peu près {length} et {weight}. Les bébés en bonne santé s’écartent beaucoup de ces moyennes.',
    },
    {
      question: 'Quels symptômes sont normaux à {n} semaines ?',
      answer: 'Les plus fréquents cette semaine sont listés plus haut. Contactez votre médecin ou votre sage-femme en cas de saignement abondant, de douleur intense, de fièvre ou de changement dans les mouvements de votre bébé.',
    },
  ],
  monthsLabel: 'environ {months} mois',
};
