import type { WeekPhrasebook } from './types';

export const itWeeks: WeekPhrasebook = {
  slugTemplate: 'settimana-{n}',
  seoTitle: '{n} settimane di gravidanza: sviluppo, sintomi e consigli',
  seoDescription:
    'Alla {n}ª settimana di gravidanza il tuo bambino è grande più o meno come {size}. Scopri cosa si sviluppa questa settimana, come cambia il tuo corpo e i sintomi più comuni.',
  intro:
    'Alla settimana {n} di gravidanza il tuo bambino è grande più o meno come {size}. Sei nel {trimester}, e questa settimana porta con sé i suoi piccoli cambiamenti — per il tuo bambino e per te.',
  trimesterInline: ['primo trimestre', 'secondo trimestre', 'terzo trimestre'],
  introEarly:
    'La settimana {n} si conta dal primo giorno dell’ultima mestruazione, quindi precede il concepimento. Conta comunque: il tuo corpo sta preparando le condizioni necessarie a una gravidanza.',
  expect: [
    'L’inizio della gravidanza è invisibile fuori e rumorosissimo dentro. I disturbi vanno e vengono di giorno in giorno, ed è normale. Mancano {left} settimane: questa settimana contano il riposo, il cibo leggero e la prima visita.',
    'I mesi centrali sono di solito la parte più serena della gravidanza. L’energia torna, la pancia si vede, le visite diventano una routine. Mancano {left} settimane: è il momento giusto per organizzarti mentre stai bene.',
    'L’ultimo tratto chiede molto al tuo corpo. Dormire è più difficile, i movimenti rallentano, le visite si infittiscono. Mancano {left} settimane: riposa, impara a riconoscere i segnali del travaglio e tieni la borsa pronta.',
  ],
  sizes: {
    not_yet: 'niente ancora — il concepimento non è avvenuto',
    poppy_seed: 'un seme di papavero',
    sesame_seed: 'un seme di sesamo',
    lentil: 'una lenticchia',
    blueberry: 'un mirtillo',
    raspberry: 'un lampone',
    grape: 'un acino d’uva',
    kumquat: 'un mandarino cinese',
    fig: 'un fico',
    lime: 'un lime',
    lemon: 'un limone',
    peach: 'una pesca',
    apple: 'una mela',
    avocado: 'un avocado',
    pear: 'una pera',
    bell_pepper: 'un peperone',
    mango: 'un mango',
    banana: 'una banana',
    carrot: 'una carota',
    papaya: 'una papaya',
    grapefruit: 'un pompelmo',
    corn: 'una pannocchia',
    cauliflower: 'un cavolfiore',
    lettuce: 'un cespo di lattuga',
    cabbage: 'un cavolo cappuccio',
    eggplant: 'una melanzana',
    squash: 'una zucca butternut',
    cucumber: 'un cetriolo',
    coconut: 'una noce di cocco',
    napa_cabbage: 'un cavolo cinese',
    pineapple: 'un ananas',
    cantaloupe: 'un melone cantalupo',
    honeydew: 'un melone bianco',
    romaine: 'una lattuga romana',
    chard: 'un mazzo di bietole',
    leek: 'un porro',
    mini_watermelon: 'una piccola anguria',
    pumpkin: 'una zucca piccola',
  },
  development: {
    prep_cycle: 'Non c’è ancora nessun bambino: il tuo corpo elimina il vecchio endometrio e inizia un nuovo ciclo.',
    egg_released: 'Un ovulo completa la maturazione nel follicolo, pronto per essere rilasciato.',
    ovulation: 'L’ovulazione avviene a metà ciclo; l’ovulo resta fecondabile per circa 24 ore.',
    fertilization: 'Se uno spermatozoo incontra l’ovulo, la fecondazione avviene nella tuba.',
    cell_division: 'L’unica cellula si divide di continuo mentre viaggia verso l’utero.',
    implantation: 'L’ammasso di cellule si annida nell’endometrio: è l’impianto.',
    placenta_begins: 'Le cellule che diventeranno placenta iniziano a formarsi e a produrre hCG.',
    three_layers_form: 'Si formano tre foglietti di cellule: ognuno darà origine a parti diverse del bambino.',
    neural_tube_forms: 'Il tubo neurale si chiude e diventerà cervello e midollo spinale.',
    heart_begins_beating: 'Il minuscolo tubo cardiaco inizia a battere, all’inizio come un semplice fremito.',
    circulation_starts: 'Si formano i primi vasi sanguigni e la circolazione si mette in moto.',
    arm_leg_buds: 'Compaiono piccoli abbozzi dove cresceranno braccia e gambe.',
    facial_features_form: 'Due punti scuri segnano il posto degli occhi e la mascella prende forma.',
    brain_grows_fast: 'Il cervello cresce in fretta: circa 100 nuove cellule al minuto.',
    kidneys_form: 'Reni, fegato e polmoni iniziano a formarsi.',
    fingers_toes_webbed: 'Dita di mani e piedi si delineano, ancora unite da sottili membrane.',
    tail_disappears: 'La piccola coda embrionale scompare in questa settimana.',
    spontaneous_movements: 'Il tuo bambino si muove già da solo, troppo delicatamente perché tu lo senta.',
    all_organs_present: 'Tutti gli organi principali ci sono, anche se nessuno è ancora completo.',
    heartbeat_audible_scan: 'Il battito si vede e si sente all’ecografia precoce.',
    muscles_develop: 'I muscoli si sviluppano e le minuscole articolazioni iniziano a piegarsi.',
    embryo_becomes_fetus: 'Ora il tuo bambino si chiama feto: la fase critica di formazione degli organi è conclusa.',
    fingernails_start: 'Sulle dita compaiono i letti ungueali.',
    bones_hardening: 'La cartilagine morbida si trasforma lentamente in osso.',
    fingers_toes_separate: 'Le dita si sono separate e le unghie iniziano a crescere.',
    tooth_buds_form: 'Nelle gengive si formano le gemme dentarie, per anni futuri.',
    reflexes_begin: 'Arrivano i primi riflessi: il bambino chiude le dita e apre la bocca.',
    kidneys_make_urine: 'I reni iniziano a produrre urina, che diventa parte del liquido amniotico.',
    vocal_cords_form: 'Si formano le corde vocali, anche se il suono ha bisogno dell’aria.',
    fingerprints_form: 'Sui polpastrelli si formano impronte digitali uniche.',
    external_genitals_form: 'I genitali esterni si stanno formando e potranno essere visibili all’ecografia.',
    facial_expressions: 'I muscoli del viso entrano in funzione: il bambino può aggrottare la fronte.',
    lanugo_appears: 'Una peluria sottile, la lanugine, inizia a coprire la pelle.',
    sucking_reflex: 'Compare il riflesso di suzione: il bambino può trovare il pollice.',
    hearing_begins: 'Le ossa dell’orecchio interno si induriscono e arrivano i primi suoni.',
    taste_buds_form: 'Si formano le papille gustative, che percepiscono i sapori del liquido amniotico.',
    coordinated_movements: 'I movimenti diventano più fluidi e coordinati.',
    hears_your_voice: 'Il tuo bambino sente la tua voce, il tuo battito e la tua digestione.',
    eyes_move_slowly: 'Gli occhi si muovono lentamente sotto le palpebre chiuse.',
    fat_under_skin: 'Si forma il grasso bruno sotto la pelle, utile a mantenere il calore dopo la nascita.',
    umbilical_cord_thickens: 'Il cordone ombelicale diventa più spesso e resistente.',
    sweat_glands_form: 'Sotto la pelle in formazione si sviluppano le ghiandole sudoripare.',
    hearing_sharpens: 'L’udito si affina: i rumori forti possono far sussultare il bambino.',
    myelin_forms: 'Una guaina protettiva, la mielina, inizia a rivestire i nervi.',
    yawning_hiccups: 'Il bambino sbadiglia, ha il singhiozzo e si stira nel liquido amniotico.',
    vernix_forms: 'Uno strato ceroso, la vernice caseosa, protegge la pelle dal liquido.',
    brain_maps_senses: 'Il cervello sta creando le aree per olfatto, gusto, udito, vista e tatto.',
    hair_on_head: 'Sul cuoio capelluto iniziano a crescere i capelli.',
    swallowing_practice: 'Il bambino deglutisce liquido amniotico, allenandosi a nutrirsi.',
    rapid_weight_gain: 'Da ora l’aumento di peso accelera in modo evidente.',
    taste_through_fluid: 'Quello che mangi dà sapore al liquido amniotico e il bambino lo assaggia.',
    marrow_makes_blood: 'Il midollo osseo prende in carico la produzione dei globuli rossi.',
    grip_develops: 'Il bambino afferra il cordone e tocca ciò che lo circonda.',
    eyebrows_visible: 'Sopracciglia e ciglia sono ormai visibili.',
    lungs_prepare: 'Nei polmoni si formano le ramificazioni che un giorno porteranno l’aria.',
    responds_to_sound: 'Voci familiari e musica possono farlo muovere o calmare.',
    skin_less_transparent: 'La pelle diventa meno trasparente man mano che si pigmenta.',
    lungs_make_surfactant: 'I polmoni iniziano a produrre surfattante, che li terrà aperti dopo la nascita.',
    inner_ear_complete: 'L’orecchio interno è completo e aiuta anche l’equilibrio.',
    hair_gets_colour: 'I capelli iniziano a prendere colore.',
    responds_to_light: 'Una luce forte sulla pancia può farlo girare dall’altra parte.',
    eyes_open: 'Le palpebre si aprono per la prima volta.',
    brain_waves_respond: 'Le onde cerebrali rispondono ora a suoni e tocco.',
    practices_breathing: 'Il bambino si allena a respirare con il liquido amniotico.',
    sleep_wake_cycles: 'Compaiono cicli chiari di sonno e veglia, spesso diversi dai tuoi.',
    recognises_voices: 'Il tuo bambino riconosce la tua voce e può calmarsi quando parli.',
    dreams_rem: 'Inizia il sonno REM, la fase associata ai sogni.',
    blinking: 'Il bambino sbatte le palpebre e le ciglia sono complete.',
    bones_need_calcium: 'Le ossa si induriscono in fretta e attingono calcio dalla tua alimentazione.',
    muscles_lungs_mature: 'Muscoli e polmoni continuano a maturare con costanza.',
    lanugo_disappears: 'La lanugine sottile inizia a scomparire.',
    all_senses_working: 'Tutti e cinque i sensi sono ormai attivi.',
    kicks_stronger: 'I calci si sentono più forti perché lo spazio si riduce.',
    head_down_position: 'Molti bambini si girano a testa in giù in questo periodo: c’è ancora spazio per cambiare.',
    fingernails_reach_tips: 'Le unghie arrivano alla punta delle dita.',
    immune_transfer: 'Gli anticorpi passano da te al bambino e costruiscono le prime difese.',
    skull_stays_soft: 'Le ossa del cranio restano morbide e separate per passare nel canale del parto.',
    lungs_nearly_ready: 'I polmoni sono quasi pronti a respirare aria.',
    vernix_thickens: 'La vernice caseosa si ispessisce per proteggere la pelle.',
    eyes_focus: 'Il bambino mette a fuoco da vicino e segue la luce.',
    kidneys_fully_developed: 'I reni sono completamente sviluppati e il fegato elabora alcune scorie.',
    skin_smooths: 'Il grasso riempie la pelle e le pieghe si distendono.',
    gripping_strength: 'La presa è forte abbastanza da stringere il tuo dito dopo la nascita.',
    meconium_builds: 'Nell’intestino si accumula il meconio, le prime feci scure.',
    fat_layers_finish: 'Si completano gli ultimi strati di grasso, utili a regolare la temperatura.',
    lungs_ready: 'I polmoni sono pronti, mentre cervello e sistema nervoso continuano a maturare.',
    ready_for_birth: 'Il tuo bambino è pronto a nascere e continua a crescere fino al travaglio.',
  },
  body: {
    period_starts: 'La mestruazione segna il giorno uno: da qui si contano le settimane di gravidanza.',
    uterus_lining_sheds: 'L’endometrio si sfalda e ne inizia a crescere uno nuovo.',
    fertile_window: 'Sei nei giorni più fertili del ciclo.',
    cervical_mucus_changes: 'Il muco cervicale diventa trasparente ed elastico intorno all’ovulazione.',
    hormones_rising: 'I livelli ormonali salgono con costanza per sostenere la gravidanza iniziale.',
    uterus_lining_thickens: 'L’endometrio si ispessisce in vista dell’impianto.',
    hcg_detectable: 'L’hCG diventa rilevabile: è ciò che misura il test di gravidanza.',
    missed_period_soon: 'Il ciclo sarebbe atteso ora: il ritardo è spesso il primo segnale.',
    blood_volume_rises: 'Il volume del sangue continua ad aumentare per nutrire la placenta.',
    uterus_grows_slightly: 'L’utero cresce, anche se dall’esterno non si nota nulla.',
    breast_changes: 'Il seno è più pieno e le areole possono scurirsi.',
    mucus_plug_forms: 'Nel collo dell’utero si forma il tappo mucoso che lo sigilla.',
    uterus_size_orange: 'Il tuo utero ha più o meno le dimensioni di una grande arancia.',
    skin_changes_body: 'La maggiore circolazione può rendere la pelle luminosa — o più impura.',
    waist_thickens: 'I pantaloni stringono già in vita, prima che si veda la pancia.',
    uterus_rises_pelvis: 'L’utero risale dalla pelvi e si può percepire in basso.',
    nausea_may_ease: 'Per molte donne la nausea inizia ad attenuarsi in questo periodo.',
    energy_returns: 'L’energia torna man mano che gli ormoni si stabilizzano.',
    showing_starts: 'Una piccola pancia diventa visibile, soprattutto a fine giornata.',
    uterus_grows_steadily: 'Da qui in avanti l’utero cresce circa un centimetro a settimana.',
    nasal_membranes_swell: 'L’aumento del flusso sanguigno gonfia le mucose del naso.',
    fundal_height_navel: 'Il fondo dell’utero è circa a metà strada verso l’ombelico.',
    ligaments_soften: 'I legamenti si ammorbidiscono e si allungano per fare spazio.',
    balance_shifts: 'Il baricentro si sposta e i movimenti cambiano.',
    first_movements: 'I primi movimenti si sentono di solito tra la 18ª e la 22ª settimana.',
    appetite_grows: 'L’appetito aumenta perché il bambino cresce più in fretta.',
    skin_pigment_changes: 'Le variazioni di pigmento sono comuni: la linea scura sulla pancia, macchie sul viso.',
    uterus_at_navel: 'Il fondo dell’utero raggiunge l’ombelico, il riferimento classico della 20ª settimana.',
    weight_gain_steady: 'L’aumento di peso diventa regolare, in genere qualche etto a settimana.',
    braxton_hicks: 'Possono comparire le contrazioni di Braxton Hicks: prove, non travaglio.',
    colostrum_may_appear: 'Dal seno possono uscire poche gocce di colostro.',
    fundal_height_above_navel: 'L’utero si trova ormai qualche centimetro sopra l’ombelico.',
    pelvis_loosens: 'Il bacino si allenta per effetto della relaxina.',
    sleep_harder: 'Trovare una posizione comoda per dormire diventa più difficile.',
    ribs_pressure: 'L’utero che cresce spinge verso le costole.',
    blood_pressure_watch: 'A ogni visita si controllano pressione e urine per escludere la preeclampsia.',
    antenatal_visits_increase: 'Da adesso le visite di controllo diventano più frequenti.',
    heartburn_more: 'Lo stomaco ha meno spazio e il bruciore diventa più frequente.',
    fatigue_returns: 'La stanchezza del terzo trimestre torna, spesso all’improvviso.',
    less_room_lungs: 'I polmoni hanno meno spazio e i respiri profondi costano fatica.',
    fundal_height_high: 'Il fondo dell’utero è alto, appena sotto le costole.',
    appetite_smaller: 'Pasti piccoli si digeriscono meglio: per uno stomaco pieno non c’è più spazio.',
    swelling_common: 'Un lieve gonfiore a mani, piedi e caviglie è comune.',
    back_pressure: 'Il peso davanti mette sotto pressione costante la parte bassa della schiena.',
    less_room_movement: 'I movimenti sembrano più rotolii e spinte che calci.',
    lightening_drop: 'Il bambino può scendere nel bacino: è l’impegno della testa.',
    cervix_softens: 'Il collo dell’utero si ammorbidisce e inizia ad accorciarsi.',
    mucus_plug: 'Il tappo mucoso può staccarsi giorni o ore prima del travaglio.',
    contractions_may_start: 'Le contrazioni possono iniziare da un momento all’altro.',
    cervix_dilates: 'Con il travaglio vero il collo dell’utero inizia a dilatarsi.',
  },
  symptoms: {
    period_symptoms: 'I soliti disturbi mestruali: crampi e una sensazione di pesantezza',
    fatigue: 'Stanchezza profonda, anche dopo una notte intera di sonno',
    mood_swings: 'Umore che cambia in fretta, per effetto degli ormoni',
    ovulation_signs: 'Una fitta da un lato e perdite trasparenti ed elastiche',
    breast_tenderness: 'Seno teso e più pesante',
    increased_appetite: 'Un appetito nettamente maggiore',
    no_symptoms_yet: 'Di solito nulla: è troppo presto per qualsiasi segnale',
    bloating: 'Gonfiore e una sensazione di pancia tesa',
    light_spotting: 'Perdite leggere, che possono essere da impianto',
    nausea: 'Nausea che può arrivare a qualsiasi ora del giorno',
    frequent_urination: 'Bisogno di andare in bagno più spesso',
    heightened_smell: 'Un olfatto più acuto che rende sgradevoli odori familiari',
    food_aversions: 'Avversioni e voglie alimentari molto forti',
    headaches: 'Mal di testa, spesso legato agli ormoni o alla disidratazione',
    constipation: 'Stitichezza, perché la digestione rallenta',
    heartburn: 'Bruciore di stomaco e reflusso, soprattutto dopo i pasti',
    nausea_easing: 'Nausea che finalmente inizia a passare',
    dizziness: 'Capogiri quando ti alzi troppo in fretta',
    nasal_congestion: 'Naso chiuso senza alcun raffreddore',
    round_ligament_pain: 'Fitte brevi nel basso ventre quando ti muovi',
    forgetfulness: 'Smemoratezza e difficoltà di concentrazione',
    skin_changes: 'Cambiamenti della pelle: macchie scure, linea sulla pancia o brufoli',
    nosebleeds: 'Qualche epistassi e gengive che sanguinano',
    leg_cramps: 'Crampi alle gambe, di solito di notte',
    back_ache: 'Un dolore sordo nella parte bassa della schiena',
    vivid_dreams: 'Sogni insolitamente vividi',
    swollen_ankles: 'Piedi e caviglie gonfi a fine giornata',
    hip_pain: 'Dolore alle anche, soprattutto sdraiata su un fianco',
    shortness_breath: 'Fiato corto con più facilità',
    discharge_increase: 'Più perdite vaginali, liquide e biancastre',
    stretch_marks_itch: 'Pelle della pancia tesa e pruriginosa',
    varicose_veins: 'Vene varicose alle gambe',
    hemorrhoids: 'Emorroidi, peggiorate dalla stitichezza',
    insomnia: 'Sonno interrotto e difficoltà a stare comoda',
    braxton_hicks_symptom: 'Indurimenti indolori della pancia che vanno e vengono',
    restless_legs: 'Gambe senza riposo la sera',
    pelvic_pressure: 'Forte pressione in basso, nel bacino',
    carpal_tunnel: 'Dita formicolanti o intorpidite, soprattutto al mattino',
    easier_breathing: 'Respiro più facile una volta che il bambino scende',
    nesting_energy: 'Una voglia improvvisa di pulire, sistemare e preparare',
    loose_stools: 'Feci più molli, che possono precedere il travaglio',
    contractions: 'Contrazioni sempre più lunghe, forti e ravvicinate',
  },
  tips: {
    start_folic_acid: 'Prendi 400 µg di acido folico al giorno: protegge il tubo neurale prima ancora che tu sappia di essere incinta.',
    track_cycle: 'Monitora il ciclo: saprai quali sono i giorni fertili e la datazione sarà più precisa.',
    avoid_alcohol_smoking: 'Elimina alcol e fumo e fai controllare al medico ogni farmaco che prendi.',
    gentle_movement: 'Muoviti con dolcezza: una camminata quotidiana aiuta circolazione, umore e sonno.',
    prenatal_vitamin: 'Assumi un integratore prenatale con acido folico e vitamina D.',
    hydrate: 'Bevi acqua durante la giornata: la disidratazione peggiora stanchezza e mal di testa.',
    take_test: 'Il test casalingo è più affidabile dal giorno in cui aspetti il ciclo.',
    book_first_appointment: 'Prenota la prima visita: di solito si fa tra la 8ª e la 12ª settimana.',
    small_frequent_meals: 'Fai pasti piccoli e frequenti: lo stomaco vuoto peggiora la nausea.',
    rest_when_tired: 'Riposa senza sensi di colpa. La stanchezza del primo trimestre è reale e passeggera.',
    first_scan_booking: 'Organizza l’ecografia di datazione, di solito tra la 10ª e la 14ª settimana.',
    talk_about_worries: 'Parla con qualcuno di cui ti fidi di come ti senti: preoccuparsi è normale.',
    fiber_rich_foods: 'Aggiungi fibre — verdura, avena, legumi — per aiutare la digestione.',
    first_trimester_screening: 'Parla con il medico o l’ostetrica dei test di screening del primo trimestre.',
    iron_rich_foods: 'Abbina alimenti ricchi di ferro alla vitamina C per assorbirlo meglio.',
    tell_employer: 'Decidi quando informare il datore di lavoro e verifica le tutele previste.',
    sleep_on_side: 'Inizia ad abituarti a dormire su un fianco, preferibilmente il sinistro.',
    maternity_clothes: 'Passa a vite morbide prima che i vestiti diventino scomodi.',
    moisturise_skin: 'Idrata la pancia ogni giorno: non evita le smagliature, ma calma il prurito.',
    pelvic_floor_exercises: 'Allena il pavimento pelvico ogni giorno: serve adesso e dopo il parto.',
    talk_and_sing: 'Parla, leggi o canta alla pancia: il tuo bambino inizia a sentire.',
    anomaly_scan_booking: 'Prenota la morfologica, di solito tra la 18ª e la 22ª settimana.',
    supportive_shoes: 'Indossa scarpe stabili: i legamenti rilassati rendono le caviglie meno sicure.',
    anomaly_scan: 'L’ecografia morfologica controlla in dettaglio organi, crescita e placenta.',
    rest_and_elevate_feet: 'Tieni le gambe sollevate quando puoi, per ridurre il gonfiore.',
    sun_protection: 'Usa la protezione solare: in gravidanza la pelle si macchia più facilmente.',
    start_kick_awareness: 'Inizia a osservare come e quando si muove il tuo bambino.',
    birth_plan: 'Comincia a pensare a come e dove vorresti partorire.',
    glucose_test_soon: 'Il test per il diabete gestazionale è previsto tra la 24ª e la 28ª settimana.',
    antenatal_classes: 'Iscriviti al corso preparto: i corsi buoni si riempiono presto.',
    glucose_test: 'Fai la curva glicemica se ti viene proposta.',
    count_movements_daily: 'Impara il ritmo quotidiano del tuo bambino e chiama se cambia.',
    monitor_blood_pressure: 'Segnala subito mal di testa, disturbi della vista o gonfiori improvvisi.',
    hospital_bag_list: 'Inizia la lista per la borsa dell’ospedale: prepararla può aspettare.',
    blood_tests_check: 'In questo periodo si controlla l’anemia; se sei Rh negativa ti verrà proposta l’immunoglobulina anti-D.',
    calcium_rich_foods: 'Includi alimenti ricchi di calcio: le ossa del bambino si stanno indurendo in fretta.',
    rest_and_nap: 'Concediti brevi riposi se le notti sono spezzate: la stanchezza si accumula.',
    breastfeeding_prep: 'Informati sull’allattamento, così i primi giorni saranno meno spiazzanti.',
    hospital_bag: 'Prepara la borsa per l’ospedale: dalla 36ª settimana deve essere pronta.',
    know_labour_signs: 'Impara i segnali del travaglio: contrazioni regolari, rottura delle acque, sanguinamento.',
    monitor_swelling: 'Un gonfiore improvviso a viso o mani va valutato lo stesso giorno.',
    install_car_seat: 'Installa e prova l’ovetto adesso, con calma.',
    group_b_strep_test: 'Chiedi del tampone per lo streptococco di gruppo B.',
    weekly_checkups: 'Da adesso i controlli diventano di solito settimanali.',
    perineal_massage: 'Il massaggio perineale dalla 34ª settimana può ridurre le lacerazioni.',
    plan_route_hospital: 'Studia il percorso verso l’ospedale e un’alternativa se chi guida non c’è.',
    postpartum_support: 'Organizza aiuto per le prime due settimane a casa: pasti, bucato, compagnia.',
    monitor_movements_closely: 'Movimenti ridotti vanno sempre controllati, anche dopo il termine.',
  },
  milestones: {
    implantation_milestone: 'Questa settimana il test di gravidanza può risultare positivo.',
    fetus_milestone: 'Il tuo bambino è ufficialmente un feto.',
    first_trimester_end: 'Fine del primo trimestre: il rischio di aborto spontaneo cala nettamente.',
    second_trimester_start: 'Benvenuta nel secondo trimestre.',
    halfway: 'Sei a metà strada.',
    viability: 'Da questa settimana i bambini nati prematuri hanno concrete possibilità di sopravvivere con cure intensive.',
    third_trimester_start: 'Inizia il terzo trimestre.',
    early_term: 'La tua gravidanza è ora considerata a termine precoce.',
    full_term: 'Il tuo bambino è a termine.',
    due_date: 'È la settimana della data presunta: solo un bambino su venti nasce esattamente quel giorno.',
  },
  faq: [
    {
      question: 'A quanti mesi corrispondono {n} settimane di gravidanza?',
      answer: '{n} settimane corrispondono a {months}. I mesi non si dividono in settimane esatte, per questo contare in settimane è più preciso.',
    },
    {
      question: 'Quanto è grande il bambino a {n} settimane?',
      answer: 'A {n} settimane il tuo bambino è grande più o meno come {size}: circa {length} e {weight}. I bambini sani variano molto rispetto a queste medie.',
    },
    {
      question: 'Quali sintomi sono normali a {n} settimane?',
      answer: 'I più frequenti di questa settimana sono elencati sopra. Contatta il medico o l’ostetrica in caso di sanguinamento abbondante, dolore intenso, febbre o cambiamenti nei movimenti del bambino.',
    },
  ],
  monthsLabel: 'circa {months} mesi',
};
