import type { WeekPhrasebook } from './types';

export const ptWeeks: WeekPhrasebook = {
  slugTemplate: 'semana-{n}',
  seoTitle: '{n} semanas de gravidez: desenvolvimento, sintomas e dicas',
  seoDescription:
    'Às {n} semanas de gravidez o teu bebé tem mais ou menos o tamanho de {size}. Vê o que se desenvolve esta semana, como muda o teu corpo e os sintomas mais comuns.',
  intro:
    'Às {n} semanas de gravidez o teu bebé tem mais ou menos o tamanho de {size}. Estás no {trimester}, e esta semana traz as suas próprias mudanças — para o teu bebé e para ti.',
  trimesterInline: ['primeiro trimestre', 'segundo trimestre', 'terceiro trimestre'],
  introEarly:
    'A semana {n} conta-se a partir do primeiro dia da última menstruação, por isso acontece antes da conceção. Ainda assim importa: o teu corpo está a preparar as condições de que uma gravidez precisa.',
  expect: [
    'O início da gravidez é invisível por fora e muito barulhento por dentro. Os sintomas vão e vêm de um dia para o outro, e isso é normal. Faltam {left} semanas: esta semana o que conta é o descanso, a comida leve e a primeira consulta.',
    'Os meses do meio costumam ser a fase mais estável da gravidez. A energia volta, a barriga aparece e as consultas tornam-se rotina. Faltam {left} semanas: é boa altura para organizares o que vem a seguir enquanto te sentes bem.',
    'A reta final exige muito do teu corpo. Dormir custa mais, os movimentos abrandam e as consultas ficam mais próximas. Faltam {left} semanas: descansa, aprende a reconhecer os sinais do parto e deixa a mala pronta.',
  ],
  sizes: {
    not_yet: 'ainda nada — a conceção ainda não aconteceu',
    poppy_seed: 'uma semente de papoila',
    sesame_seed: 'uma semente de sésamo',
    lentil: 'uma lentilha',
    blueberry: 'um mirtilo',
    raspberry: 'uma framboesa',
    grape: 'uma uva',
    kumquat: 'uma kumquat',
    fig: 'um figo',
    lime: 'uma lima',
    lemon: 'um limão',
    peach: 'um pêssego',
    apple: 'uma maçã',
    avocado: 'um abacate',
    pear: 'uma pera',
    bell_pepper: 'um pimento',
    mango: 'uma manga',
    banana: 'uma banana',
    carrot: 'uma cenoura',
    papaya: 'uma papaia',
    grapefruit: 'uma toranja',
    corn: 'uma espiga de milho',
    cauliflower: 'uma couve-flor',
    lettuce: 'uma alface',
    cabbage: 'uma couve-coração',
    eggplant: 'uma beringela',
    squash: 'uma abóbora-manteiga',
    cucumber: 'um pepino',
    coconut: 'um coco',
    napa_cabbage: 'uma couve chinesa',
    pineapple: 'um ananás',
    cantaloupe: 'uma meloa cantalupo',
    honeydew: 'um melão branco',
    romaine: 'uma alface romana',
    chard: 'um molho de acelgas',
    leek: 'um alho-francês',
    mini_watermelon: 'uma melancia pequena',
    pumpkin: 'uma abóbora pequena',
  },
  development: {
    prep_cycle: 'Ainda não há bebé: o teu corpo elimina o endométrio antigo e começa um novo ciclo.',
    egg_released: 'Um óvulo acaba de amadurecer dentro do folículo, pronto a ser libertado.',
    ovulation: 'A ovulação acontece a meio do ciclo; o óvulo pode ser fecundado durante cerca de 24 horas.',
    fertilization: 'Se um espermatozoide encontra o óvulo, a fecundação dá-se na trompa.',
    cell_division: 'A célula única divide-se sem parar enquanto viaja até ao útero.',
    implantation: 'O conjunto de células instala-se no endométrio — é a implantação.',
    placenta_begins: 'As células que vão formar a placenta começam a desenvolver-se e produzem hCG.',
    three_layers_form: 'Formam-se três camadas de células; cada uma dará origem a partes diferentes do bebé.',
    neural_tube_forms: 'O tubo neural fecha-se e vai tornar-se cérebro e medula espinhal.',
    heart_begins_beating: 'O minúsculo tubo cardíaco começa a bater, ao início como um simples tremor.',
    circulation_starts: 'Formam-se os primeiros vasos sanguíneos e a circulação arranca.',
    arm_leg_buds: 'Aparecem pequenos botões onde vão crescer os braços e as pernas.',
    facial_features_form: 'Dois pontos escuros marcam o lugar dos olhos e o maxilar ganha forma.',
    brain_grows_fast: 'O cérebro cresce depressa: cerca de 100 células novas por minuto.',
    kidneys_form: 'Os rins, o fígado e os pulmões começam a formar-se.',
    fingers_toes_webbed: 'Formam-se os dedos das mãos e dos pés, ainda unidos por membranas finas.',
    tail_disappears: 'A pequena cauda embrionária desaparece esta semana.',
    spontaneous_movements: 'O teu bebé já se mexe sozinho, de forma demasiado suave para sentires.',
    all_organs_present: 'Todos os órgãos principais já existem, embora nenhum esteja terminado.',
    heartbeat_audible_scan: 'O batimento costuma ver-se e ouvir-se numa ecografia precoce.',
    muscles_develop: 'Os músculos desenvolvem-se e as pequenas articulações começam a dobrar.',
    embryo_becomes_fetus: 'O teu bebé chama-se agora feto: a fase crítica de formação dos órgãos terminou.',
    fingernails_start: 'Aparecem os leitos das unhas nos dedos das mãos e dos pés.',
    bones_hardening: 'A cartilagem mole vai lentamente transformando-se em osso.',
    fingers_toes_separate: 'Os dedos já estão separados e as unhas começam a crescer.',
    tooth_buds_form: 'Nas gengivas formam-se os gérmenes dentários, para daqui a anos.',
    reflexes_begin: 'Surgem os primeiros reflexos: o bebé fecha os dedos e abre a boca.',
    kidneys_make_urine: 'Os rins começam a produzir urina, que passa a fazer parte do líquido amniótico.',
    vocal_cords_form: 'Formam-se as cordas vocais, ainda que o som precise de ar para viajar.',
    fingerprints_form: 'Nas pontas dos dedos formam-se impressões digitais únicas.',
    external_genitals_form: 'Os genitais externos estão a formar-se e poderão ver-se numa ecografia posterior.',
    facial_expressions: 'Os músculos da cara entram em ação: o bebé consegue franzir a testa.',
    lanugo_appears: 'Uma penugem fina, o lanugo, começa a cobrir a pele.',
    sucking_reflex: 'Surge o reflexo de sucção; o bebé pode encontrar o polegar.',
    hearing_begins: 'Os ossos do ouvido interno endurecem e chegam os primeiros sons.',
    taste_buds_form: 'Formam-se as papilas gustativas, que captam os sabores do líquido amniótico.',
    coordinated_movements: 'Os movimentos tornam-se mais suaves e coordenados.',
    hears_your_voice: 'O teu bebé ouve a tua voz, o teu coração e a tua digestão.',
    eyes_move_slowly: 'Os olhos movem-se devagar por trás das pálpebras fechadas.',
    fat_under_skin: 'Forma-se gordura castanha sob a pele, que ajudará a manter o calor após o nascimento.',
    umbilical_cord_thickens: 'O cordão umbilical fica mais grosso e resistente.',
    sweat_glands_form: 'Sob a pele em formação desenvolvem-se as glândulas sudoríparas.',
    hearing_sharpens: 'A audição apura-se; barulhos fortes podem sobressaltar o bebé.',
    myelin_forms: 'Uma camada protetora chamada mielina começa a revestir os nervos.',
    yawning_hiccups: 'O teu bebé boceja, tem soluços e espreguiça-se no líquido amniótico.',
    vernix_forms: 'Uma camada cerosa, o vérnix, protege a pele do líquido.',
    brain_maps_senses: 'O cérebro está a criar as áreas do olfato, do paladar, da audição, da visão e do tato.',
    hair_on_head: 'Começa a crescer cabelo na cabeça.',
    swallowing_practice: 'O teu bebé engole líquido amniótico e treina para mamar.',
    rapid_weight_gain: 'A partir daqui o ganho de peso acelera claramente.',
    taste_through_fluid: 'O que comes dá sabor ao líquido amniótico e o teu bebé prova-o.',
    marrow_makes_blood: 'A medula óssea assume a produção dos glóbulos vermelhos.',
    grip_develops: 'O teu bebé agarra o cordão umbilical e toca no que o rodeia.',
    eyebrows_visible: 'As sobrancelhas e as pestanas já se veem.',
    lungs_prepare: 'Nos pulmões formam-se as ramificações que um dia levarão o ar.',
    responds_to_sound: 'Vozes conhecidas e música podem fazê-lo mexer-se ou acalmar.',
    skin_less_transparent: 'A pele fica menos transparente à medida que ganha pigmento.',
    lungs_make_surfactant: 'Os pulmões começam a produzir surfactante, que os manterá abertos ao nascer.',
    inner_ear_complete: 'O ouvido interno está completo e ajuda também no equilíbrio.',
    hair_gets_colour: 'O cabelo começa a ganhar cor.',
    responds_to_light: 'Uma luz forte na barriga pode fazê-lo virar-se para o outro lado.',
    eyes_open: 'As pálpebras abrem-se pela primeira vez.',
    brain_waves_respond: 'As ondas cerebrais já respondem ao som e ao toque.',
    practices_breathing: 'O teu bebé treina movimentos respiratórios com líquido amniótico.',
    sleep_wake_cycles: 'Surgem ciclos claros de sono e vigília, muitas vezes diferentes dos teus.',
    recognises_voices: 'O teu bebé reconhece a tua voz e pode acalmar quando falas.',
    dreams_rem: 'Começa o sono REM, a fase associada aos sonhos.',
    blinking: 'O teu bebé consegue pestanejar e as pestanas estão completas.',
    bones_need_calcium: 'Os ossos endurecem depressa e vão buscar cálcio à tua alimentação.',
    muscles_lungs_mature: 'Os músculos e os pulmões continuam a amadurecer de forma constante.',
    lanugo_disappears: 'O lanugo fino começa a desaparecer.',
    all_senses_working: 'Os cinco sentidos já funcionam.',
    kicks_stronger: 'Os pontapés sentem-se mais fortes porque o espaço diminui.',
    head_down_position: 'Muitos bebés viram-se de cabeça para baixo nesta altura: ainda há espaço para mudar.',
    fingernails_reach_tips: 'As unhas chegam à ponta dos dedos.',
    immune_transfer: 'Os anticorpos passam de ti para o bebé e criam as primeiras defesas.',
    skull_stays_soft: 'Os ossos do crânio ficam moles e separados para passar no canal de parto.',
    lungs_nearly_ready: 'Os pulmões estão quase prontos para respirar ar.',
    vernix_thickens: 'A camada de vérnix engrossa para proteger a pele.',
    eyes_focus: 'O teu bebé foca ao perto e segue a luz.',
    kidneys_fully_developed: 'Os rins estão totalmente desenvolvidos e o fígado processa alguns resíduos.',
    skin_smooths: 'A gordura preenche a pele e as rugas alisam.',
    gripping_strength: 'A força da mão já chega para agarrar o teu dedo depois de nascer.',
    meconium_builds: 'No intestino acumula-se o mecónio, as primeiras fezes escuras.',
    fat_layers_finish: 'Completam-se as últimas camadas de gordura, que ajudam a regular a temperatura.',
    lungs_ready: 'Os pulmões estão prontos e o cérebro e o sistema nervoso continuam a amadurecer.',
    ready_for_birth: 'O teu bebé está pronto para nascer e continua a crescer até ao parto.',
  },
  body: {
    period_starts: 'A menstruação marca o dia um: é daqui que se contam as semanas de gravidez.',
    uterus_lining_sheds: 'O endométrio descama e começa a formar-se um novo.',
    fertile_window: 'Estás nos dias mais férteis do ciclo.',
    cervical_mucus_changes: 'O muco cervical fica transparente e elástico na altura da ovulação.',
    hormones_rising: 'Os níveis hormonais sobem de forma constante para sustentar a gravidez inicial.',
    uterus_lining_thickens: 'O endométrio engrossa à espera da implantação.',
    hcg_detectable: 'A hCG passa a ser detetável: é isso que o teste de gravidez mede.',
    missed_period_soon: 'A menstruação seria agora; o atraso é muitas vezes o primeiro sinal.',
    blood_volume_rises: 'O teu volume de sangue continua a aumentar para alimentar a placenta.',
    uterus_grows_slightly: 'O útero cresce, embora por fora ainda não se note.',
    breast_changes: 'O peito fica mais cheio e as aréolas podem escurecer.',
    mucus_plug_forms: 'No colo do útero forma-se o rolhão mucoso, que o sela.',
    uterus_size_orange: 'O teu útero tem mais ou menos o tamanho de uma laranja grande.',
    skin_changes_body: 'A maior circulação pode deixar a pele luminosa — ou com mais borbulhas.',
    waist_thickens: 'A cintura aperta antes de haver barriga à vista.',
    uterus_rises_pelvis: 'O útero sobe para fora da bacia e já se sente em baixo.',
    nausea_may_ease: 'Em muitas mulheres as náuseas começam a aliviar por esta altura.',
    energy_returns: 'A energia regressa à medida que as hormonas estabilizam.',
    showing_starts: 'Já se vê uma pequena barriga, sobretudo ao fim do dia.',
    uterus_grows_steadily: 'A partir daqui o útero cresce cerca de um centímetro por semana.',
    nasal_membranes_swell: 'O aumento do fluxo sanguíneo incha as mucosas do nariz.',
    fundal_height_navel: 'O fundo do útero está a meio caminho do umbigo.',
    ligaments_soften: 'Os ligamentos amolecem e esticam para dar espaço.',
    balance_shifts: 'O teu centro de gravidade muda e os movimentos sentem-se diferentes.',
    first_movements: 'Os primeiros movimentos sentem-se normalmente entre as semanas 18 e 22.',
    appetite_grows: 'O apetite aumenta porque o bebé ganha peso mais depressa.',
    skin_pigment_changes: 'As alterações de pigmento são comuns: a linha escura na barriga e manchas na cara.',
    uterus_at_navel: 'O fundo do útero chega ao umbigo — a referência clássica das 20 semanas.',
    weight_gain_steady: 'O ganho de peso torna-se regular, normalmente algumas centenas de gramas por semana.',
    braxton_hicks: 'Podem começar as contrações de Braxton Hicks: são de treino, não de parto.',
    colostrum_may_appear: 'Do peito podem sair umas gotas de colostro.',
    fundal_height_above_navel: 'O útero está já alguns centímetros acima do umbigo.',
    pelvis_loosens: 'A bacia solta-se por efeito da relaxina.',
    sleep_harder: 'Encontrar uma posição confortável para dormir é cada vez mais difícil.',
    ribs_pressure: 'O útero, a crescer, pressiona as costelas.',
    blood_pressure_watch: 'Em cada consulta verificam-se a tensão e a urina, à procura de sinais de pré-eclâmpsia.',
    antenatal_visits_increase: 'A partir de agora as consultas costumam ser mais frequentes.',
    heartburn_more: 'O estômago tem menos espaço e a azia aparece mais vezes.',
    fatigue_returns: 'O cansaço do terceiro trimestre regressa, muitas vezes de repente.',
    less_room_lungs: 'Os pulmões têm menos espaço e respirar fundo custa mais.',
    fundal_height_high: 'O fundo do útero está alto, mesmo por baixo das costelas.',
    appetite_smaller: 'Refeições pequenas caem melhor: já não há espaço para um estômago cheio.',
    swelling_common: 'É comum um inchaço ligeiro nas mãos, nos pés e nos tornozelos.',
    back_pressure: 'O peso à frente faz pressão constante na zona lombar.',
    less_room_movement: 'Os movimentos parecem mais rolamentos e empurrões do que pontapés.',
    lightening_drop: 'O bebé pode descer para a bacia — é o chamado encaixe.',
    cervix_softens: 'O colo do útero amolece e começa a encurtar.',
    mucus_plug: 'O rolhão mucoso pode sair dias ou horas antes do parto.',
    contractions_may_start: 'As contrações podem começar a qualquer momento.',
    cervix_dilates: 'Quando o trabalho de parto começa a sério, o colo do útero dilata.',
  },
  symptoms: {
    period_symptoms: 'Desconfortos normais da menstruação: cólicas e uma sensação pesada',
    fatigue: 'Cansaço profundo, mesmo depois de uma noite inteira de sono',
    mood_swings: 'Humor que muda depressa, por causa das hormonas',
    ovulation_signs: 'Uma pontada de um lado e corrimento transparente e elástico',
    breast_tenderness: 'Peito sensível e mais pesado',
    increased_appetite: 'Um apetite claramente maior',
    no_symptoms_yet: 'Normalmente nada: é cedo demais para haver sinais',
    bloating: 'Inchaço e uma sensação de barriga tensa',
    light_spotting: 'Perdas ligeiras, que podem ser hemorragia de implantação',
    nausea: 'Náuseas que podem aparecer a qualquer hora do dia',
    frequent_urination: 'Vontade de ir à casa de banho mais vezes',
    heightened_smell: 'Um olfato mais apurado que torna desagradáveis cheiros familiares',
    food_aversions: 'Aversões e desejos alimentares muito fortes',
    headaches: 'Dores de cabeça, muitas vezes ligadas às hormonas ou à falta de líquidos',
    constipation: 'Prisão de ventre, porque a digestão abranda',
    heartburn: 'Azia e refluxo, sobretudo depois das refeições',
    nausea_easing: 'Náuseas que finalmente começam a passar',
    dizziness: 'Tonturas quando te levantas depressa demais',
    nasal_congestion: 'Nariz entupido sem qualquer constipação',
    round_ligament_pain: 'Picadas curtas na parte baixa da barriga quando te mexes',
    forgetfulness: 'Esquecimentos e dificuldade em concentrar-te',
    skin_changes: 'Alterações na pele: manchas escuras, linha na barriga ou borbulhas',
    nosebleeds: 'Hemorragias nasais ocasionais e gengivas sensíveis',
    leg_cramps: 'Cãibras nas pernas, quase sempre à noite',
    back_ache: 'Uma dor surda na zona lombar',
    vivid_dreams: 'Sonhos invulgarmente vívidos',
    swollen_ankles: 'Pés e tornozelos inchados ao fim do dia',
    hip_pain: 'Ancas doridas, sobretudo deitada de lado',
    shortness_breath: 'Ficas sem ar com mais facilidade',
    discharge_increase: 'Mais corrimento vaginal, fluido e esbranquiçado',
    stretch_marks_itch: 'Pele esticada e com comichão sobre a barriga',
    varicose_veins: 'Varizes nas pernas',
    hemorrhoids: 'Hemorroidas, agravadas pela prisão de ventre',
    insomnia: 'Sono interrompido e dificuldade em ficar confortável',
    braxton_hicks_symptom: 'Endurecimentos indolores da barriga que vão e vêm',
    restless_legs: 'Pernas inquietas ao fim do dia',
    pelvic_pressure: 'Muita pressão em baixo, na bacia',
    carpal_tunnel: 'Formigueiro ou dedos dormentes, sobretudo de manhã',
    easier_breathing: 'Respiras melhor assim que o bebé desce',
    nesting_energy: 'Uma vontade súbita de limpar, arrumar e preparar tudo',
    loose_stools: 'Fezes mais moles, que podem anteceder o parto',
    contractions: 'Contrações cada vez mais longas, fortes e seguidas',
  },
  tips: {
    start_folic_acid: 'Toma 400 µg de ácido fólico por dia: protege o tubo neural mesmo antes de saberes que estás grávida.',
    track_cycle: 'Regista o teu ciclo: ficas a conhecer os dias férteis e a datação será mais precisa.',
    avoid_alcohol_smoking: 'Deixa o álcool e o tabaco e confirma com o médico qualquer medicação.',
    gentle_movement: 'Mexe-te com suavidade: uma caminhada diária ajuda a circulação, o humor e o sono.',
    prenatal_vitamin: 'Toma um suplemento pré-natal com ácido fólico e vitamina D.',
    hydrate: 'Bebe água ao longo do dia; a desidratação agrava o cansaço e as dores de cabeça.',
    take_test: 'O teste caseiro é mais fiável a partir do dia em que esperas a menstruação.',
    book_first_appointment: 'Marca a primeira consulta de vigilância: costuma ser entre as semanas 8 e 12.',
    small_frequent_meals: 'Come pouco e muitas vezes: o estômago vazio agrava as náuseas.',
    rest_when_tired: 'Descansa sem culpa. O cansaço do primeiro trimestre é real e passageiro.',
    first_scan_booking: 'Marca a ecografia do primeiro trimestre, normalmente entre as semanas 10 e 14.',
    talk_about_worries: 'Fala com alguém de confiança sobre o que sentes: preocupares-te é normal.',
    fiber_rich_foods: 'Junta fibra — legumes, aveia, leguminosas — para a digestão não parar.',
    first_trimester_screening: 'Fala com o médico ou a parteira sobre o rastreio do primeiro trimestre.',
    iron_rich_foods: 'Combina alimentos ricos em ferro com vitamina C para absorver melhor.',
    tell_employer: 'Decide quando contar à entidade patronal e confirma os teus direitos.',
    sleep_on_side: 'Começa a habituar-te a dormir de lado, de preferência o esquerdo.',
    maternity_clothes: 'Passa a cinturas macias antes de a roupa começar a incomodar.',
    moisturise_skin: 'Hidrata a barriga todos os dias: não evita as estrias, mas alivia a comichão.',
    pelvic_floor_exercises: 'Faz exercícios do pavimento pélvico todos os dias; ajudam agora e depois do parto.',
    talk_and_sing: 'Fala, lê ou canta para a barriga: o teu bebé começa a ouvir.',
    anomaly_scan_booking: 'Marca a ecografia morfológica, normalmente entre as semanas 18 e 22.',
    supportive_shoes: 'Usa calçado estável: os ligamentos mais soltos deixam os tornozelos menos seguros.',
    anomaly_scan: 'A ecografia morfológica avalia em detalhe os órgãos, o crescimento e a placenta.',
    rest_and_elevate_feet: 'Põe os pés para cima sempre que puderes, para aliviar o inchaço.',
    sun_protection: 'Usa protetor solar: na gravidez a pele mancha com mais facilidade.',
    start_kick_awareness: 'Começa a reparar em como e quando o teu bebé se mexe.',
    birth_plan: 'Começa a pensar nas tuas preferências de parto e no sítio onde queres ter o bebé.',
    glucose_test_soon: 'O teste da diabetes gestacional está para breve, entre as semanas 24 e 28.',
    antenatal_classes: 'Inscreve-te no curso de preparação para o parto: os bons enchem-se cedo.',
    glucose_test: 'Faz a prova de tolerância à glicose quando te for proposta.',
    count_movements_daily: 'Aprende o padrão diário do teu bebé e liga se ele mudar.',
    monitor_blood_pressure: 'Comunica de imediato dores de cabeça, alterações da visão ou inchaço súbito.',
    hospital_bag_list: 'Começa a lista da mala da maternidade; fazê-la pode esperar.',
    blood_tests_check: 'Por esta altura verifica-se a anemia; se tiveres Rh negativo será proposta a imunoglobulina anti-D.',
    calcium_rich_foods: 'Inclui alimentos ricos em cálcio: os ossos do teu bebé estão a endurecer depressa.',
    rest_and_nap: 'Faz sestas curtas se as noites forem partidas; o cansaço acumula-se.',
    breastfeeding_prep: 'Informa-te sobre a amamentação para os primeiros dias serem menos estranhos.',
    hospital_bag: 'Prepara a mala da maternidade para estar pronta a partir das 36 semanas.',
    know_labour_signs: 'Conhece os sinais de parto: contrações regulares, rutura das águas, hemorragia.',
    monitor_swelling: 'Um inchaço súbito na cara ou nas mãos deve ser avaliado no próprio dia.',
    install_car_seat: 'Instala e testa a cadeirinha do carro agora, sem pressas.',
    group_b_strep_test: 'Pergunta pelo rastreio do estreptococo do grupo B.',
    weekly_checkups: 'A partir de agora as consultas costumam passar a semanais.',
    perineal_massage: 'A massagem perineal a partir das 34 semanas pode reduzir as lacerações.',
    plan_route_hospital: 'Planeia o caminho para a maternidade e uma alternativa, caso quem conduz não esteja.',
    postpartum_support: 'Organiza ajuda para as duas primeiras semanas em casa: refeições, roupa, companhia.',
    monitor_movements_closely: 'Menos movimentos é sempre motivo para ligar, mesmo depois da data prevista.',
  },
  milestones: {
    implantation_milestone: 'Esta semana um teste de gravidez já pode dar positivo.',
    fetus_milestone: 'O teu bebé é oficialmente um feto.',
    first_trimester_end: 'Fim do primeiro trimestre: o risco de aborto espontâneo desce bastante.',
    second_trimester_start: 'Bem-vinda ao segundo trimestre.',
    halfway: 'Estás a meio caminho.',
    viability: 'A partir desta semana, os bebés nascidos cedo demais têm hipóteses reais de sobreviver com cuidados intensivos.',
    third_trimester_start: 'Começa o terceiro trimestre.',
    early_term: 'A tua gravidez é agora considerada de termo precoce.',
    full_term: 'O teu bebé está de termo.',
    due_date: 'É a semana da data prevista: só cerca de um em cada vinte bebés nasce exatamente nesse dia.',
  },
  faq: [
    {
      question: 'Quantos meses são {n} semanas de gravidez?',
      answer: '{n} semanas correspondem a {months}. Os meses não se dividem em semanas exatas, por isso contar em semanas é mais preciso.',
    },
    {
      question: 'Qual é o tamanho do bebé às {n} semanas?',
      answer: 'Às {n} semanas o teu bebé tem mais ou menos o tamanho de {size}: cerca de {length} e {weight}. Bebés saudáveis variam muito em relação a estas médias.',
    },
    {
      question: 'Que sintomas são normais às {n} semanas?',
      answer: 'Os mais frequentes desta semana estão em cima. Contacta o médico ou a parteira se tiveres hemorragia abundante, dor intensa, febre ou notares mudanças nos movimentos do bebé.',
    },
  ],
  monthsLabel: 'cerca de {months} meses',
};
